theme: jekyll-theme-cayman
title: Stats CPA 2021
description: Pàgina de l'assignatura d'Introducció a l'Estadística del Grau en CPA (UdG) per al curs 2020-21
show_downloads: true 
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
