<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Anàlisi de variables i ordenació de dades</title>

<script src="site_libs/header-attrs-2.7/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Stats CPA</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Inici</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Elements bàsics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="primerspassos.html">Primeres passes</a>
    </li>
    <li>
      <a href="importacio.html">Importar i exportar arxius</a>
    </li>
    <li>
      <a href="objectes.html">Objectes i funcions bàsiques</a>
    </li>
  </ul>
</li>
<li>
  <a href="ordenacio.html">Ordenació de variables</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Anàlisi de variables i ordenació de dades</h1>

</div>


<div id="variables-i-ordenació-de-data.frames-en-r" class="section level3">
<h3>Variables i ordenació de data.frames en R</h3>
<div id="primer-pas" class="section level4">
<h4>Primer pas</h4>
<p>Recordem que treballarem amb el projecte que tenim obert per a les classes pràctiques i que vam crear el primer dia.</p>
</div>
</div>
<div id="les-variables-a-r" class="section level3">
<h3>Les variables a R</h3>
<p>R és un programa d’anàlisi estadístic de dades que ens permet analitzar, descriure i operar amb variables com les que hem acabat d’estudiar. Ens permet aplicar totes les tècniques estadístiques que veurem al llarg de les properes sessions però també ens permet recopilar dades i emmagatzemar-les d’una determinada forma. Per tant, en les bases de dades que carreguem a R identificar totes les tipologies de variables que hem estudiat a nivell teòric.</p>
<p>Tanmateix, hem de tenir clar abans d’analitzar una variable a R provinent d’una determinada base de dades el que caracteritza a cada tipus de variable, quina forma prenen i quin tipus d’informació volem obtenir. En aquest apartat farem un repàs de com les trobarem en el programa R.</p>
<div id="les-variables-categòriques-nominals-en-r" class="section level4">
<h4>Les variables categòriques nominals en R</h4>
<p>En primer lloc, tenim tres tipus de variables categòriques (nominals, ordinals o binàries), que podem emmagatzemar a R com a vectors de caràcter, factors o vectors lògics:</p>
<p>• Com a vectors de caràcter</p>
<p>Els vectors de caràcter o strings emmagatzemen tot tipus de caràcters, des de lletres fins a símbols especials. Sempre utilitzarem les cometes per a referir-nos a cada valor.</p>
<p>Crearem un vector de caràcter a R de la següent manera:</p>
<pre class="r"><code>vector_caracter &lt;- c(&quot;Kuwait&quot;, &quot;Qatar&quot;, &quot;Saudi Arabia&quot;, &quot;Bahrain&quot;)</code></pre>
<p>• Com a vectors enters en forma de factors</p>
<p>Un factor és un vector enter que emmagatzema informació categòrica. Normalment crearem els factors a partir d’un vector caràcter i el passarem a factor amb la funció factor() o as.factor().</p>
<p>Primera forma de crear-ho:</p>
<pre class="r"><code>paisos &lt;- factor(c(&quot;BRA&quot;, &quot;ARG&quot;, &quot;VEN&quot;, &quot;URU&quot;, &quot;PAR&quot;)) </code></pre>
<p>Segona forma de crear-ho. Creem un vector de caràcter:</p>
<pre class="r"><code>paisos &lt;- c(&quot;BRA&quot;, &quot;ARG&quot;, &quot;VEN&quot;, &quot;URU&quot;, &quot;PAR&quot;)</code></pre>
<p>El transformem en un factor amb la funció as.factor():</p>
<pre class="r"><code>as.factor(paisos)</code></pre>
<pre><code>## [1] BRA ARG VEN URU PAR
## Levels: ARG BRA PAR URU VEN</code></pre>
<p>Observem el vector i les seves categories:</p>
<pre class="r"><code>paisos</code></pre>
<pre><code>## [1] &quot;BRA&quot; &quot;ARG&quot; &quot;VEN&quot; &quot;URU&quot; &quot;PAR&quot;</code></pre>
<pre class="r"><code>levels(paisos)</code></pre>
<pre><code>## NULL</code></pre>
<p>Ara podem modificar els nivells o canviar els noms de la següent manera:</p>
<pre class="r"><code>levels(paisos) &lt;- c(&quot;Brazil&quot;,&quot;Argentina&quot;,&quot;Venezuela&quot;, &quot;Uruguay&quot;, &quot;Paraguay&quot;)
paisos #Comprovem el resultat</code></pre>
<pre><code>## [1] &quot;BRA&quot; &quot;ARG&quot; &quot;VEN&quot; &quot;URU&quot; &quot;PAR&quot;
## attr(,&quot;levels&quot;)
## [1] &quot;Brazil&quot;    &quot;Argentina&quot; &quot;Venezuela&quot; &quot;Uruguay&quot;   &quot;Paraguay&quot;</code></pre>
<p>Si volem també podem modificar les categories a través d’un argument a la funció factor().</p>
<pre class="r"><code>factor(paisos, labels = c(&quot;Argentina&quot;, &quot;Brazil&quot;, &quot;Paraguay&quot;, &quot;Uruguay&quot;, &quot;Venezuela&quot;))</code></pre>
<pre><code>## [1] Brazil    Argentina Venezuela Uruguay   Paraguay 
## Levels: Argentina Brazil Paraguay Uruguay Venezuela</code></pre>
<p>• Com a vectors lògics</p>
<p>Les variables categòriques nominals també poden prendre la forma d’un vector lògic, en què la variable només pot tenir dos valors discrets i normalment no ordenables: veritat (TRUE) i fals (FALSE). En aquest cas es tractarà d’una variable binària (també dita dicotòmica, booleana o dummy), que normalment serveix per a indicar la presència o absència d’un determinat concepte. Si el concepte és present, la variable pren el valor lògic TRUE, si el concepte és absent, pren el valor lògic FALSE.</p>
<p>Per comprovar-ho, crearem un vector lògic de la següent manera:</p>
<pre class="r"><code>vector_logic &lt;- c(TRUE, FALSE, FALSE, TRUE)</code></pre>
</div>
<div id="les-variables-categòriques-ordinals-en-r" class="section level4">
<h4>Les variables categòriques ordinals en R</h4>
<p>Les variables ordinals són variables categòriques que es poden ordenar de manera lògica. És a dir, segueixen un ordre determinat. Aquestes variables les podem emmagatzemar com a vectors de caràcter, factors o vectors lògics, encara que amb algunes petites diferències en relació als factors i els vectors lògics.</p>
<p>• Com a factors:</p>
<p>Els factors són una de les eines principals que tenim per a emmagatzemar variables categòriques. El seu gran potencial és la manera com poden guardar variables ordinals, ja que tenen la capacitat d’ordenar les categories seguint l’ordre que indiquem.</p>
<p>El seu gran potencial és la manera com poden guardar variables ordinals, ja que tenen la capacitat d’ordenar les categories seguint l’ordre que indiquem.</p>
<pre class="r"><code>wb &lt;- data.frame(country = c(&quot;Antigua and Barbuda&quot;, &quot;Belize&quot;, &quot;Costa Rica&quot;, &quot;Dominica&quot;, &quot;Dominican Republic&quot;,
                             &quot;El Salvador&quot;, &quot;Guyana&quot;, &quot;Guatemala&quot;, &quot;Haiti&quot;, &quot;Honduras&quot;, &quot;Jamaica&quot;, &quot;Nicaragua&quot;, 
                             &quot;Panama&quot;, &quot;Surinam&quot;, &quot;Trinidad and Tobago&quot;), 
                 income = factor(c(&quot;high&quot;, &quot;upper-middle&quot;, &quot;upper-middle&quot;,&quot;upper-middle&quot;, &quot;upper-middle&quot;, 
                                   &quot;lower-middle&quot;, &quot;upper-middle&quot;, &quot;upper-middle&quot;,&quot;low&quot;, &quot;lower-middle&quot;, &quot;upper-middle&quot;,
                                   &quot;lower-middle&quot;, &quot;high&quot;, &quot;upper-middle&quot;, &quot;high&quot;)),
                 stringsAsFactors = FALSE)</code></pre>
<p>Imprimim el marc de dades teclejant wb. Fixeu-vos en el procediment per convertir un factor en ordinal:</p>
<p>• A dins de la funció factor(), indiquem que l’argument order a TRUE.</p>
<p>• Indiquem a l’argument levels l’ordre dels factors, de menor a major.</p>
<pre class="r"><code>wb$income &lt;- factor(wb$income, order = TRUE, levels = c(&quot;low&quot;, &quot;lower-middle&quot;, &quot;upper-middle&quot;, &quot;high&quot;))</code></pre>
<p>Comproveu el resultat amb:</p>
<pre class="r"><code>class(wb$income)</code></pre>
<pre><code>## [1] &quot;ordered&quot; &quot;factor&quot;</code></pre>
<pre class="r"><code>wb$income</code></pre>
<pre><code>##  [1] high         upper-middle upper-middle upper-middle upper-middle lower-middle
##  [7] upper-middle upper-middle low          lower-middle upper-middle lower-middle
## [13] high         upper-middle high        
## Levels: low &lt; lower-middle &lt; upper-middle &lt; high</code></pre>
<p>• Com a vectors lògics</p>
<p>Els vectors lògics també poden operar com a variable categòrica ordinal pel simple fet que TRUE és convertible a 1 i FALSE és convertible a 0.</p>
<p>Fixem-nos què passa si convertim un vector lògic a vector numèric:</p>
<pre class="r"><code>as.numeric(c(TRUE, FALSE))</code></pre>
<pre><code>## [1] 1 0</code></pre>
<p>Això significa que TRUE pot ser interpretat com un 1 i FALSE com un 0. Però no son números amb un valor per operar de manera numèrica. Sinó que son categories.</p>
<p>Per il·lustrar-ho crearem un marc de dades format per dos vectors, country i poverty. Primer creem els vectors i, a partir dels vectors, creem el marc de dades:</p>
<pre class="r"><code>country = c(&quot;Armenia&quot;, &quot;Austria&quot;, &quot;Benin&quot;, &quot;Bolivia&quot;, &quot;Brazil&quot;, &quot;Colombia&quot;, 
            &quot;El Salvador&quot;, &quot;Ethiopia&quot;, &quot;Honduras&quot;, &quot;Indonesia&quot;)
poverty = c(1.90, 0.7, 49.6, 6.4, 3.4, 4.5, 1.9, 26.7, 16.2, 7.2)
pov &lt;- data.frame(country, poverty)</code></pre>
<p>Observeu com qualsevol vector és convertible en un vector lògic. Mireu els següents exemples:</p>
<p>• Preguntem si algun element del vector country porta el nom Benin.</p>
<pre class="r"><code>pov$country == &quot;Benin&quot;</code></pre>
<pre><code>##  [1] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE</code></pre>
<p>• Preguntem si algun element del vector poverty és inferior a 16.</p>
<pre class="r"><code>pov$poverty &lt; 16</code></pre>
<pre><code>##  [1]  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE</code></pre>
<p>Per passar qualsevol tipus de vector a vector lògic haurem de dominar els operadors relacionals. En aquest enllaç teniu un video sobre com fer servir operadors relacionals. És molt important el seu us a R.</p>
</div>
<div id="les-variables-categòriques-binàries-en-r" class="section level4">
<h4>Les variables categòriques binàries en R</h4>
<p>Les variables categòriques binàries només poden adoptar dos valors. Es poden crear amb vectors de caràcter, factors o vectors lògics, tal com s’ha mostrat en els anteriors apartats.</p>
<p>• Com a caràcter:</p>
<pre class="r"><code>sexe = c(&quot;Home&quot;, &quot;Dona&quot;)</code></pre>
<p>• Com a factor:</p>
<pre class="r"><code>sexe &lt;- factor(c(&quot;Home&quot;,&quot;Dona&quot;))
as.factor(sexe)</code></pre>
<pre><code>## [1] Home Dona
## Levels: Dona Home</code></pre>
<p>• Com a vector lògic:</p>
<pre class="r"><code>sexe &lt;- c(TRUE, FALSE) 
class(sexe)</code></pre>
<pre><code>## [1] &quot;logical&quot;</code></pre>
</div>
<div id="les-variables-numèriques-en-r" class="section level4">
<h4>Les variables numèriques en R</h4>
<p>Les variables numèriques, anomenades també cardinals o quantitatives, són variables que representen nombres en els seus valors. Hi ha dos tipus de variables numèriques:</p>
<p>• Les numèriques contínues accepten decimals.</p>
<p>• Les numèriques discretes no accepten decimals.</p>
<p>Per defecte, si una variable conté nombres ens crearà un vector numèric, també anomenat double. Per crear un vector enter ho podem fer de dues maneres diferents:</p>
<pre class="r"><code>enter1 &lt;- c(4L, 8L, 15L, 16L, 23L, 42L)
typeof(enter1)</code></pre>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<p>La lletra L darrera del número determina que és un número enter, és a dir, sense decimal.</p>
<pre class="r"><code>enter2 &lt;- as.integer(c(4, 8, 15, 16, 23, 42))
typeof(enter2)</code></pre>
<pre><code>## [1] &quot;integer&quot;</code></pre>
<p>Utilitzant la funció as.integer li estem dient a R que aquests números son enters, és a dir, una variable numèrica discreta.</p>
<p>Aquesta, en canvi, és una variable numèrica continua.</p>
<pre class="r"><code>temp_2020 &lt;- c(10.3, 11.4, 15.7, 17.2, 20.8, 24.3, 27.4, 30.2, 26.5, 20.2, 16.5, 13.2)
class(temp_2020)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>A l’hora de fer operacions amb un vector numèric o enter, podem fer dues coses:</p>
<p>• Fer operacions d’un vector amb un nombre.</p>
<pre class="r"><code>3 * c(1, 3, 6)</code></pre>
<pre><code>## [1]  3  9 18</code></pre>
<p>• Fer operacions entre dos vectors d’igual longitud.</p>
<pre class="r"><code>c(1, 3, 6) * c(1, 3, 6)</code></pre>
<pre><code>## [1]  1  9 36</code></pre>
<p>• En canvi, en operacions amb vectors de diferent longitud ens donarà un avís.</p>
<pre class="r"><code>c(1, 3, 6) * c(1, 3)</code></pre>
<pre><code>## Warning in c(1, 3, 6) * c(1, 3): longer object length is not a multiple of shorter
## object length</code></pre>
<pre><code>## [1] 1 9 6</code></pre>
</div>
</div>
<div id="exploració-bàsica-de-bases-de-dades-i-variables.-funcions-per-obtenir-informació-dels-objectes-i-de-les-variables-a-r." class="section level3">
<h3>Exploració bàsica de bases de dades i variables. Funcions per obtenir informació dels objectes i de les variables a R.</h3>
<p>Utilitzem l’anterior data.frame:</p>
<pre class="r"><code>wb &lt;- data.frame(country = c(&quot;Antigua and Barbuda&quot;, &quot;Belize&quot;, &quot;Costa Rica&quot;, &quot;Dominica&quot;, &quot;Dominican Republic&quot;,
                             &quot;El Salvador&quot;, &quot;Guyana&quot;, &quot;Guatemala&quot;, &quot;Haiti&quot;, &quot;Honduras&quot;, &quot;Jamaica&quot;, &quot;Nicaragua&quot;, 
                             &quot;Panama&quot;, &quot;Surinam&quot;, &quot;Trinidad and Tobago&quot;), 
                 income = factor(c(&quot;high&quot;, &quot;upper-middle&quot;, &quot;upper-middle&quot;,&quot;upper-middle&quot;, &quot;upper-middle&quot;, 
                                   &quot;lower-middle&quot;, &quot;upper-middle&quot;, &quot;upper-middle&quot;,&quot;low&quot;, &quot;lower-middle&quot;, &quot;upper-middle&quot;,
                                   &quot;lower-middle&quot;, &quot;high&quot;, &quot;upper-middle&quot;, &quot;high&quot;)),
                 stringsAsFactors = FALSE)</code></pre>
<p>Carreguem la llibreria tidyverse que és útil per l’observació, ordenació i transformació de dades:</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<p>Utilitzem la funció class() sobre les variables:</p>
<pre class="r"><code>class(wb$income) #### Es ordinal</code></pre>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<pre class="r"><code>class(wb$country) #### Es nominal</code></pre>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>Utilitzem la funció glimpse() sobre la base de dades i les variables:</p>
<pre class="r"><code>glimpse(wb)</code></pre>
<pre><code>## Rows: 15
## Columns: 2
## $ country &lt;chr&gt; &quot;Antigua and Barbuda&quot;, &quot;Belize&quot;, &quot;Costa Rica&quot;, &quot;Dominica&quot;, &quot;Domini~
## $ income  &lt;fct&gt; high, upper-middle, upper-middle, upper-middle, upper-middle, lowe~</code></pre>
<p>Ens dona informació de les fileres (número de casos), quantes variables (columnes) tenim i quin tipus son (character and factor).</p>
<pre class="r"><code>glimpse(wb$country)</code></pre>
<pre><code>##  chr [1:15] &quot;Antigua and Barbuda&quot; &quot;Belize&quot; &quot;Costa Rica&quot; &quot;Dominica&quot; ...</code></pre>
<p>Ens diu que és un vector de caràcter que ocupa les posicions del 1 al 15 de casos i ens assenyalar els primers noms.</p>
<pre class="r"><code>glimpse(wb$income)</code></pre>
<pre><code>##  Factor w/ 4 levels &quot;high&quot;,&quot;low&quot;,&quot;lower-middle&quot;,..: 1 4 4 4 4 3 4 4 2 3 ...</code></pre>
<p>Ens diu que es un factor ordinal amb 4 nivells: high, low, lower-middle i upper-middle.</p>
<p>Utilitzem la funció attributes() sobre la base de dades i les variables:</p>
<pre class="r"><code>attributes(wb)</code></pre>
<pre><code>## $names
## [1] &quot;country&quot; &quot;income&quot; 
## 
## $class
## [1] &quot;data.frame&quot;
## 
## $row.names
##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15</code></pre>
<p>Ens diu el nom de les dues variables de la base de dades, allò que és el nostre objecte (una base de dades o data.frame) i el número de casos (15).</p>
<pre class="r"><code>attributes(wb$country)</code></pre>
<pre><code>## NULL</code></pre>
<p>No funciona amb variables qualitatives nominals.</p>
<pre class="r"><code>attributes(wb$income)</code></pre>
<pre><code>## $levels
## [1] &quot;high&quot;         &quot;low&quot;          &quot;lower-middle&quot; &quot;upper-middle&quot;
## 
## $class
## [1] &quot;factor&quot;</code></pre>
<p>En canvi, amb variables qualitatives ordinals, sí: ens diu les categories de la variable i la classe d’objecte que és: un factor.</p>
<p>Fem el mateix que hem fet amb la funció unclass():</p>
<pre class="r"><code>unclass(wb)</code></pre>
<pre><code>## $country
##  [1] &quot;Antigua and Barbuda&quot; &quot;Belize&quot;              &quot;Costa Rica&quot;         
##  [4] &quot;Dominica&quot;            &quot;Dominican Republic&quot;  &quot;El Salvador&quot;        
##  [7] &quot;Guyana&quot;              &quot;Guatemala&quot;           &quot;Haiti&quot;              
## [10] &quot;Honduras&quot;            &quot;Jamaica&quot;             &quot;Nicaragua&quot;          
## [13] &quot;Panama&quot;              &quot;Surinam&quot;             &quot;Trinidad and Tobago&quot;
## 
## $income
##  [1] high         upper-middle upper-middle upper-middle upper-middle lower-middle
##  [7] upper-middle upper-middle low          lower-middle upper-middle lower-middle
## [13] high         upper-middle high        
## Levels: high low lower-middle upper-middle
## 
## attr(,&quot;row.names&quot;)
##  [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15</code></pre>
<p>Ens dona tota la informació del data.frame: categories de la primera variable (country) i de la segona (income) i el número total de casos (15).</p>
<pre class="r"><code>unclass(wb$country)</code></pre>
<pre><code>##  [1] &quot;Antigua and Barbuda&quot; &quot;Belize&quot;              &quot;Costa Rica&quot;         
##  [4] &quot;Dominica&quot;            &quot;Dominican Republic&quot;  &quot;El Salvador&quot;        
##  [7] &quot;Guyana&quot;              &quot;Guatemala&quot;           &quot;Haiti&quot;              
## [10] &quot;Honduras&quot;            &quot;Jamaica&quot;             &quot;Nicaragua&quot;          
## [13] &quot;Panama&quot;              &quot;Surinam&quot;             &quot;Trinidad and Tobago&quot;</code></pre>
<p>Ens dona totes les categories de la variable nominal country.</p>
<pre class="r"><code>unclass(wb$income)</code></pre>
<pre><code>##  [1] 1 4 4 4 4 3 4 4 2 3 4 3 1 4 1
## attr(,&quot;levels&quot;)
## [1] &quot;high&quot;         &quot;low&quot;          &quot;lower-middle&quot; &quot;upper-middle&quot;</code></pre>
<p>Ens dona els nivells o categories ordinals i com s’ordenen en el total de casos.</p>
<p>Comprovem això amb dades reals. Utilitzarem la base de dades d’enquestes del ICPS des del 1991 fins al 2019. Carreguem la library (foreign) o (readr) per poder obrir els dos arxius que tenen diferent format.</p>
<pre class="r"><code>#library(foreign)</code></pre>
<p>Carreguem també la library(tidyverse) per poder obrir funcions d’exploració de dades:</p>
<pre class="r"><code>#library(tidyverse)</code></pre>
<p>Carreguem el de la base de dades de l’enquesta del ICPS:</p>
<pre class="r"><code>ICPS &lt;- read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;)</code></pre>
<pre><code>## re-encoding from CP1252</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Duplicated levels in factor V371: Per mi és tan important la llibertat com la
## igualtat, però s</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 added in variable: V480</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 added in variable: V481</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 added in variable: V482</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
## 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
## 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
## 60, 61, 62, 63, 64 added in variable: V519</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
## 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
## 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
## 60, 61, 62, 67 added in variable: V520</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
## 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
## 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 60, 61, 62, 64
## added in variable: V521</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
## 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
## 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 58, 59, 62 added in
## variable: V522</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 6, 10, 11, 12, 14, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27,
## 28, 29, 31, 32, 34, 36, 37, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53,
## 54, 55, 57, 60 added in variable: V523</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 9, 12, 13, 17, 21, 22, 23, 25, 29, 30, 32, 37, 40, 41, 43, 45,
## 46, 49, 50, 52, 55, 56, 57, 62 added in variable: V524</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 25, 28, 31, 33, 42, 44, 45, 47, 49, 50, 59 added in variable:
## V525</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 30, 51, 55 added in variable: V526</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 32 added in variable: V527</code></pre>
<pre class="r"><code>as_tibble(ICPS)</code></pre>
<pre><code>## # A tibble: 37,972 x 573
##    NUMERO ANY    ID01  ID02  ID03  ID11  ID12  ID13  ID14  ID15  ID21 ID22H ID22D
##     &lt;dbl&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1      5 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  2     10 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  3     12 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  4     15 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  5     42 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  6    134 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  7    149 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  8    150 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  9    209 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
## 10    219 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
## # ... with 37,962 more rows, and 560 more variables: ID31 &lt;dbl&gt;, ID41 &lt;dbl&gt;,
## #   IDI &lt;fct&gt;, V001 &lt;fct&gt;, V002 &lt;fct&gt;, V003 &lt;fct&gt;, V004 &lt;fct&gt;, V005 &lt;fct&gt;,
## #   V006 &lt;fct&gt;, V007 &lt;fct&gt;, V008 &lt;fct&gt;, V009 &lt;fct&gt;, V010 &lt;fct&gt;, V011 &lt;fct&gt;,
## #   V012 &lt;fct&gt;, V013 &lt;fct&gt;, V014 &lt;fct&gt;, V015 &lt;fct&gt;, V016 &lt;fct&gt;, V017 &lt;fct&gt;,
## #   V018 &lt;fct&gt;, V019 &lt;fct&gt;, V020 &lt;fct&gt;, V021 &lt;fct&gt;, V022 &lt;fct&gt;, V023 &lt;fct&gt;,
## #   V024 &lt;fct&gt;, V025 &lt;fct&gt;, V026 &lt;fct&gt;, V027 &lt;fct&gt;, V028 &lt;fct&gt;, V029 &lt;fct&gt;,
## #   V030 &lt;fct&gt;, V031 &lt;fct&gt;, V032 &lt;fct&gt;, V033 &lt;fct&gt;, V034 &lt;fct&gt;, V035 &lt;fct&gt;,
## #   V036 &lt;fct&gt;, V037 &lt;fct&gt;, V038 &lt;fct&gt;, V039 &lt;fct&gt;, V040 &lt;fct&gt;, V041 &lt;fct&gt;,
## #   V042 &lt;fct&gt;, V043 &lt;fct&gt;, V044 &lt;fct&gt;, V045 &lt;fct&gt;, V046 &lt;fct&gt;, V047 &lt;fct&gt;,
## #   V048 &lt;fct&gt;, V049 &lt;fct&gt;, V050 &lt;fct&gt;, V051 &lt;fct&gt;, V052 &lt;fct&gt;, V053 &lt;fct&gt;,
## #   V054 &lt;fct&gt;, V055 &lt;fct&gt;, V056 &lt;fct&gt;, V057 &lt;fct&gt;, V058 &lt;fct&gt;, V059 &lt;fct&gt;,
## #   V060 &lt;fct&gt;, V061 &lt;fct&gt;, V062 &lt;fct&gt;, V063 &lt;fct&gt;, V064 &lt;fct&gt;, V065 &lt;fct&gt;,
## #   V066 &lt;fct&gt;, V067 &lt;fct&gt;, V068 &lt;fct&gt;, V069 &lt;fct&gt;, V070 &lt;fct&gt;, V071 &lt;fct&gt;,
## #   V072 &lt;fct&gt;, V073 &lt;fct&gt;, V074 &lt;fct&gt;, V075 &lt;fct&gt;, V076 &lt;fct&gt;, V077 &lt;fct&gt;,
## #   V078 &lt;fct&gt;, V079 &lt;fct&gt;, V080 &lt;fct&gt;, V081 &lt;fct&gt;, V082 &lt;fct&gt;, V083 &lt;fct&gt;,
## #   V084 &lt;fct&gt;, V085 &lt;fct&gt;, V086 &lt;fct&gt;, V087 &lt;fct&gt;, V088 &lt;fct&gt;, V089 &lt;fct&gt;,
## #   V090 &lt;fct&gt;, V091 &lt;fct&gt;, V092 &lt;fct&gt;, V093 &lt;fct&gt;, V094 &lt;fct&gt;, V095 &lt;fct&gt;,
## #   V096 &lt;fct&gt;, V097 &lt;fct&gt;, ...</code></pre>
<p>Apliquem les funcions analitzades anteriorment</p>
<pre class="r"><code>class(ICPS)</code></pre>
<pre><code>## [1] &quot;list&quot;</code></pre>
<p>Una llista és un objecte format per diverses bases de dades unides. Per tal de poder operar amb ell cal convertir-lo en un marc de dades. Ho fem de la següent manera:</p>
<pre class="r"><code>ICPS &lt;- as.data.frame(ICPS)
class(ICPS)</code></pre>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>Amb class(), el programa R ens diu que ara estem davant un data.frame.</p>
<pre class="r"><code>#glimpse(ICPS)</code></pre>
<p>Si utilitzem glimpse() podem veure com és una base de dades amb 573 variables i 37.972 casos. A més, podem veure els diferents tipus de variables que tenim. Aquesta funció ens resumeix diferents caràcterístiques d’aquest data.frame.</p>
<p>Aquestes dues funcions ens donen tota la informació de cadascuna de les variables però ens la dona de cop i és poc útil. És millor analitzar variable a variable.</p>
<p>Per últim, si volem que R ens ensenyi la totalitat de la base de dades ben ordenada podem realitzar la funció View():</p>
<pre class="r"><code>#View(ICPS)</code></pre>
<p>Ens obre una pestanya on ens indica el nom de totes les variables, el tipus que son i les seves categories o valors. Com sabem, aquestes funcions també es poden aplicar variable a variable. De fet, és més útil que en el total de la base de dades.</p>
<p>La funció names ens dona el nom de totes les variables de la base de dades analitzada.</p>
<pre class="r"><code>names(ICPS)</code></pre>
<pre><code>##   [1] &quot;NUMERO&quot;    &quot;ANY&quot;       &quot;ID01&quot;      &quot;ID02&quot;      &quot;ID03&quot;      &quot;ID11&quot;     
##   [7] &quot;ID12&quot;      &quot;ID13&quot;      &quot;ID14&quot;      &quot;ID15&quot;      &quot;ID21&quot;      &quot;ID22H&quot;    
##  [13] &quot;ID22D&quot;     &quot;ID31&quot;      &quot;ID41&quot;      &quot;IDI&quot;       &quot;V001&quot;      &quot;V002&quot;     
##  [19] &quot;V003&quot;      &quot;V004&quot;      &quot;V005&quot;      &quot;V006&quot;      &quot;V007&quot;      &quot;V008&quot;     
##  [25] &quot;V009&quot;      &quot;V010&quot;      &quot;V011&quot;      &quot;V012&quot;      &quot;V013&quot;      &quot;V014&quot;     
##  [31] &quot;V015&quot;      &quot;V016&quot;      &quot;V017&quot;      &quot;V018&quot;      &quot;V019&quot;      &quot;V020&quot;     
##  [37] &quot;V021&quot;      &quot;V022&quot;      &quot;V023&quot;      &quot;V024&quot;      &quot;V025&quot;      &quot;V026&quot;     
##  [43] &quot;V027&quot;      &quot;V028&quot;      &quot;V029&quot;      &quot;V030&quot;      &quot;V031&quot;      &quot;V032&quot;     
##  [49] &quot;V033&quot;      &quot;V034&quot;      &quot;V035&quot;      &quot;V036&quot;      &quot;V037&quot;      &quot;V038&quot;     
##  [55] &quot;V039&quot;      &quot;V040&quot;      &quot;V041&quot;      &quot;V042&quot;      &quot;V043&quot;      &quot;V044&quot;     
##  [61] &quot;V045&quot;      &quot;V046&quot;      &quot;V047&quot;      &quot;V048&quot;      &quot;V049&quot;      &quot;V050&quot;     
##  [67] &quot;V051&quot;      &quot;V052&quot;      &quot;V053&quot;      &quot;V054&quot;      &quot;V055&quot;      &quot;V056&quot;     
##  [73] &quot;V057&quot;      &quot;V058&quot;      &quot;V059&quot;      &quot;V060&quot;      &quot;V061&quot;      &quot;V062&quot;     
##  [79] &quot;V063&quot;      &quot;V064&quot;      &quot;V065&quot;      &quot;V066&quot;      &quot;V067&quot;      &quot;V068&quot;     
##  [85] &quot;V069&quot;      &quot;V070&quot;      &quot;V071&quot;      &quot;V072&quot;      &quot;V073&quot;      &quot;V074&quot;     
##  [91] &quot;V075&quot;      &quot;V076&quot;      &quot;V077&quot;      &quot;V078&quot;      &quot;V079&quot;      &quot;V080&quot;     
##  [97] &quot;V081&quot;      &quot;V082&quot;      &quot;V083&quot;      &quot;V084&quot;      &quot;V085&quot;      &quot;V086&quot;     
## [103] &quot;V087&quot;      &quot;V088&quot;      &quot;V089&quot;      &quot;V090&quot;      &quot;V091&quot;      &quot;V092&quot;     
## [109] &quot;V093&quot;      &quot;V094&quot;      &quot;V095&quot;      &quot;V096&quot;      &quot;V097&quot;      &quot;V098&quot;     
## [115] &quot;V099&quot;      &quot;V100&quot;      &quot;V101&quot;      &quot;V102&quot;      &quot;V103&quot;      &quot;V104&quot;     
## [121] &quot;V105&quot;      &quot;V106&quot;      &quot;V107&quot;      &quot;V108&quot;      &quot;V109&quot;      &quot;V110&quot;     
## [127] &quot;V111&quot;      &quot;V112&quot;      &quot;V113&quot;      &quot;V114&quot;      &quot;V115&quot;      &quot;V116&quot;     
## [133] &quot;V117&quot;      &quot;V118&quot;      &quot;V119&quot;      &quot;V120&quot;      &quot;V121&quot;      &quot;V122&quot;     
## [139] &quot;V123&quot;      &quot;V124&quot;      &quot;V125&quot;      &quot;V126&quot;      &quot;V127&quot;      &quot;V128&quot;     
## [145] &quot;V129&quot;      &quot;V130&quot;      &quot;V131&quot;      &quot;V132&quot;      &quot;V133&quot;      &quot;V134&quot;     
## [151] &quot;V135&quot;      &quot;V136&quot;      &quot;V137&quot;      &quot;V138&quot;      &quot;V139&quot;      &quot;V140&quot;     
## [157] &quot;V141&quot;      &quot;V142&quot;      &quot;V143&quot;      &quot;V144&quot;      &quot;V145&quot;      &quot;V146&quot;     
## [163] &quot;V147&quot;      &quot;V148&quot;      &quot;V149&quot;      &quot;V150&quot;      &quot;V151&quot;      &quot;V152&quot;     
## [169] &quot;V153&quot;      &quot;V154&quot;      &quot;V155&quot;      &quot;V156&quot;      &quot;V157&quot;      &quot;V158&quot;     
## [175] &quot;V159&quot;      &quot;V160&quot;      &quot;V161&quot;      &quot;V162&quot;      &quot;V163&quot;      &quot;V164&quot;     
## [181] &quot;V165&quot;      &quot;V166&quot;      &quot;V167&quot;      &quot;V168&quot;      &quot;V169&quot;      &quot;V170&quot;     
## [187] &quot;V171&quot;      &quot;V172&quot;      &quot;V173&quot;      &quot;V174&quot;      &quot;V175&quot;      &quot;V176&quot;     
## [193] &quot;V177&quot;      &quot;V178&quot;      &quot;V179&quot;      &quot;V180&quot;      &quot;V181&quot;      &quot;V182&quot;     
## [199] &quot;V183&quot;      &quot;V184&quot;      &quot;V185&quot;      &quot;V186&quot;      &quot;V187&quot;      &quot;V188&quot;     
## [205] &quot;V189&quot;      &quot;V190&quot;      &quot;V191&quot;      &quot;V192&quot;      &quot;V193&quot;      &quot;V194&quot;     
## [211] &quot;V195&quot;      &quot;V196&quot;      &quot;V197&quot;      &quot;V198&quot;      &quot;V199&quot;      &quot;V200&quot;     
## [217] &quot;V201&quot;      &quot;V202&quot;      &quot;V203&quot;      &quot;V204&quot;      &quot;V205&quot;      &quot;V206&quot;     
## [223] &quot;V207&quot;      &quot;V208&quot;      &quot;V209&quot;      &quot;V210&quot;      &quot;V211&quot;      &quot;V212&quot;     
## [229] &quot;V213&quot;      &quot;V214&quot;      &quot;V215&quot;      &quot;V216&quot;      &quot;V217&quot;      &quot;V218&quot;     
## [235] &quot;V219&quot;      &quot;V220&quot;      &quot;V221&quot;      &quot;V222&quot;      &quot;V223&quot;      &quot;V224&quot;     
## [241] &quot;V225&quot;      &quot;V226&quot;      &quot;V227&quot;      &quot;V228&quot;      &quot;V229&quot;      &quot;V230&quot;     
## [247] &quot;V231&quot;      &quot;V232&quot;      &quot;V233&quot;      &quot;V234&quot;      &quot;V235&quot;      &quot;V236&quot;     
## [253] &quot;V237&quot;      &quot;V238&quot;      &quot;V239&quot;      &quot;V240&quot;      &quot;V241&quot;      &quot;V242&quot;     
## [259] &quot;V243&quot;      &quot;V244&quot;      &quot;V245&quot;      &quot;V246&quot;      &quot;V247&quot;      &quot;V248&quot;     
## [265] &quot;V249&quot;      &quot;V250&quot;      &quot;V251&quot;      &quot;V252&quot;      &quot;V253&quot;      &quot;V254&quot;     
## [271] &quot;V255&quot;      &quot;V256&quot;      &quot;V257&quot;      &quot;V258&quot;      &quot;V259&quot;      &quot;V260&quot;     
## [277] &quot;V261&quot;      &quot;V262&quot;      &quot;V263&quot;      &quot;V264&quot;      &quot;V265&quot;      &quot;V266&quot;     
## [283] &quot;V267&quot;      &quot;V268&quot;      &quot;V269&quot;      &quot;V270&quot;      &quot;V271&quot;      &quot;V272&quot;     
## [289] &quot;V273&quot;      &quot;V274&quot;      &quot;V275&quot;      &quot;V276&quot;      &quot;V277&quot;      &quot;V278&quot;     
## [295] &quot;V279&quot;      &quot;V280&quot;      &quot;V281&quot;      &quot;V282&quot;      &quot;V283&quot;      &quot;V284&quot;     
## [301] &quot;V285&quot;      &quot;V286&quot;      &quot;V287&quot;      &quot;V288&quot;      &quot;V289&quot;      &quot;V290&quot;     
## [307] &quot;V291&quot;      &quot;V292&quot;      &quot;V293&quot;      &quot;V294&quot;      &quot;V295&quot;      &quot;V296&quot;     
## [313] &quot;V297&quot;      &quot;V298&quot;      &quot;V299&quot;      &quot;V300&quot;      &quot;V301&quot;      &quot;V302&quot;     
## [319] &quot;V303&quot;      &quot;V304&quot;      &quot;V305&quot;      &quot;V306&quot;      &quot;V307&quot;      &quot;V308&quot;     
## [325] &quot;V309&quot;      &quot;V310&quot;      &quot;V311&quot;      &quot;V312&quot;      &quot;V313&quot;      &quot;V314&quot;     
## [331] &quot;V315&quot;      &quot;V316&quot;      &quot;V317&quot;      &quot;V318&quot;      &quot;V319&quot;      &quot;V320&quot;     
## [337] &quot;V321&quot;      &quot;V322&quot;      &quot;V323&quot;      &quot;V324&quot;      &quot;V325&quot;      &quot;V326&quot;     
## [343] &quot;V327&quot;      &quot;V328&quot;      &quot;V329&quot;      &quot;V330&quot;      &quot;V331&quot;      &quot;V332&quot;     
## [349] &quot;V333&quot;      &quot;V334&quot;      &quot;V335&quot;      &quot;V336&quot;      &quot;V337&quot;      &quot;V338&quot;     
## [355] &quot;V339&quot;      &quot;V340&quot;      &quot;V341&quot;      &quot;V342&quot;      &quot;V343&quot;      &quot;V344&quot;     
## [361] &quot;V345&quot;      &quot;V346&quot;      &quot;V347&quot;      &quot;V348&quot;      &quot;V349&quot;      &quot;V350&quot;     
## [367] &quot;V351&quot;      &quot;V352&quot;      &quot;v352_2&quot;    &quot;V353&quot;      &quot;v353_2&quot;    &quot;V354&quot;     
## [373] &quot;v354_2&quot;    &quot;V355&quot;      &quot;V356&quot;      &quot;V357&quot;      &quot;V358&quot;      &quot;V359&quot;     
## [379] &quot;V360&quot;      &quot;V361&quot;      &quot;V362&quot;      &quot;V363&quot;      &quot;V364&quot;      &quot;V365&quot;     
## [385] &quot;V366&quot;      &quot;V367&quot;      &quot;V368&quot;      &quot;V369&quot;      &quot;V370&quot;      &quot;V371&quot;     
## [391] &quot;V372&quot;      &quot;V373&quot;      &quot;V374&quot;      &quot;V375&quot;      &quot;V376&quot;      &quot;V377&quot;     
## [397] &quot;V378&quot;      &quot;V379&quot;      &quot;V380&quot;      &quot;V381&quot;      &quot;V382&quot;      &quot;V383&quot;     
## [403] &quot;V384&quot;      &quot;V385&quot;      &quot;V386&quot;      &quot;V387&quot;      &quot;V388&quot;      &quot;V389&quot;     
## [409] &quot;V390&quot;      &quot;V391&quot;      &quot;V392&quot;      &quot;V393&quot;      &quot;V394&quot;      &quot;V395&quot;     
## [415] &quot;V396&quot;      &quot;V397&quot;      &quot;V398&quot;      &quot;V399&quot;      &quot;V400&quot;      &quot;V401&quot;     
## [421] &quot;V402&quot;      &quot;V403&quot;      &quot;V404&quot;      &quot;V405&quot;      &quot;V406&quot;      &quot;V407&quot;     
## [427] &quot;V408&quot;      &quot;V409&quot;      &quot;V410&quot;      &quot;V411&quot;      &quot;V412&quot;      &quot;V413&quot;     
## [433] &quot;V414&quot;      &quot;V415&quot;      &quot;V416&quot;      &quot;V417&quot;      &quot;V418&quot;      &quot;V419&quot;     
## [439] &quot;V420&quot;      &quot;V421&quot;      &quot;V422&quot;      &quot;V423&quot;      &quot;V424&quot;      &quot;V425&quot;     
## [445] &quot;V426&quot;      &quot;V427&quot;      &quot;V428&quot;      &quot;V429&quot;      &quot;V430&quot;      &quot;V431&quot;     
## [451] &quot;V432&quot;      &quot;V433&quot;      &quot;V434&quot;      &quot;V435&quot;      &quot;V436&quot;      &quot;V437&quot;     
## [457] &quot;V438&quot;      &quot;V439&quot;      &quot;V440&quot;      &quot;V441&quot;      &quot;V442&quot;      &quot;V443&quot;     
## [463] &quot;V444&quot;      &quot;V445&quot;      &quot;V446&quot;      &quot;V447&quot;      &quot;V448&quot;      &quot;V449&quot;     
## [469] &quot;V450&quot;      &quot;V451&quot;      &quot;V452&quot;      &quot;V453&quot;      &quot;V454&quot;      &quot;V455&quot;     
## [475] &quot;V456&quot;      &quot;V457&quot;      &quot;V458&quot;      &quot;V459&quot;      &quot;V460&quot;      &quot;V461&quot;     
## [481] &quot;V462&quot;      &quot;V463&quot;      &quot;V464&quot;      &quot;V465&quot;      &quot;V466&quot;      &quot;V467&quot;     
## [487] &quot;V468&quot;      &quot;V469&quot;      &quot;V470&quot;      &quot;V471&quot;      &quot;V472&quot;      &quot;V473&quot;     
## [493] &quot;V474&quot;      &quot;V475&quot;      &quot;V476&quot;      &quot;V477&quot;      &quot;V478&quot;      &quot;V479&quot;     
## [499] &quot;V480&quot;      &quot;V481&quot;      &quot;V482&quot;      &quot;V483&quot;      &quot;V484&quot;      &quot;V485&quot;     
## [505] &quot;V486&quot;      &quot;V487&quot;      &quot;V488&quot;      &quot;V489&quot;      &quot;V490&quot;      &quot;V491&quot;     
## [511] &quot;V492&quot;      &quot;V493&quot;      &quot;V494&quot;      &quot;V495&quot;      &quot;V496&quot;      &quot;V497&quot;     
## [517] &quot;V498&quot;      &quot;V499&quot;      &quot;V500&quot;      &quot;V501&quot;      &quot;V502&quot;      &quot;V503&quot;     
## [523] &quot;SEXE&quot;      &quot;EDAT&quot;      &quot;V504&quot;      &quot;V505&quot;      &quot;V506&quot;      &quot;V507&quot;     
## [529] &quot;V508&quot;      &quot;V509&quot;      &quot;V510&quot;      &quot;V511&quot;      &quot;V512&quot;      &quot;V513&quot;     
## [535] &quot;V514&quot;      &quot;V515&quot;      &quot;V516&quot;      &quot;V517&quot;      &quot;V518&quot;      &quot;V519&quot;     
## [541] &quot;V520&quot;      &quot;V521&quot;      &quot;V522&quot;      &quot;V523&quot;      &quot;V524&quot;      &quot;V525&quot;     
## [547] &quot;V526&quot;      &quot;V527&quot;      &quot;V528&quot;      &quot;V529&quot;      &quot;V530&quot;      &quot;V531&quot;     
## [553] &quot;V532&quot;      &quot;V533&quot;      &quot;V534&quot;      &quot;V535&quot;      &quot;V536&quot;      &quot;V537&quot;     
## [559] &quot;V538&quot;      &quot;V539&quot;      &quot;V540&quot;      &quot;V541&quot;      &quot;V542&quot;      &quot;V543&quot;     
## [565] &quot;V544&quot;      &quot;V545&quot;      &quot;V546&quot;      &quot;V547&quot;      &quot;V548&quot;      &quot;PROVINCIA&quot;
## [571] &quot;DIMENSIO&quot;  &quot;DISTRICTE&quot; &quot;PES&quot;</code></pre>
<p>Ara busquem les variables més facilment identificables pel seu contngut: ANY, PROVINCIA, SEXE i DIMENSIO.</p>
<pre class="r"><code>glimpse(ICPS$ANY)</code></pre>
<pre><code>##  Factor w/ 26 levels &quot;1991&quot;,&quot;1992&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<p>La funció glimpse() ens diu que any és una variable qualitativa en format factor que té 26 nivells doferents.</p>
<pre class="r"><code>class(ICPS$ANY)</code></pre>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<pre class="r"><code>attributes(ICPS$ANY) </code></pre>
<pre><code>## $levels
##  [1] &quot;1991&quot; &quot;1992&quot; &quot;1993&quot; &quot;1994&quot; &quot;1995&quot; &quot;1996&quot; &quot;1997&quot; &quot;1998&quot; &quot;1999&quot; &quot;2000&quot; &quot;2001&quot;
## [12] &quot;2002&quot; &quot;2003&quot; &quot;2004&quot; &quot;2005&quot; &quot;2006&quot; &quot;2007&quot; &quot;2008&quot; &quot;2009&quot; &quot;2010&quot; &quot;2011&quot; &quot;2012&quot;
## [23] &quot;2013&quot; &quot;2014&quot; &quot;2015&quot; &quot;2016&quot;
## 
## $class
## [1] &quot;factor&quot;</code></pre>
<pre class="r"><code>levels(ICPS$ANY)</code></pre>
<pre><code>##  [1] &quot;1991&quot; &quot;1992&quot; &quot;1993&quot; &quot;1994&quot; &quot;1995&quot; &quot;1996&quot; &quot;1997&quot; &quot;1998&quot; &quot;1999&quot; &quot;2000&quot; &quot;2001&quot;
## [12] &quot;2002&quot; &quot;2003&quot; &quot;2004&quot; &quot;2005&quot; &quot;2006&quot; &quot;2007&quot; &quot;2008&quot; &quot;2009&quot; &quot;2010&quot; &quot;2011&quot; &quot;2012&quot;
## [23] &quot;2013&quot; &quot;2014&quot; &quot;2015&quot; &quot;2016&quot;</code></pre>
<p>Ens confirma que és una variable qualitativa (factor)</p>
<p>Analitzem la variable SEXE.</p>
<pre class="r"><code>class(ICPS$SEXE)</code></pre>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<p>Ens diu que és un factor. Recordem que aquesta és una manera d’enmagatzemar a R les variables qualitatives.</p>
<pre class="r"><code>levels(ICPS$SEXE) #Ens diu que dos: &quot;Home&quot; i &quot;Dona&quot;. És una variable qualitativa dicotòmica.</code></pre>
<pre><code>## [1] &quot;Home&quot; &quot;Dona&quot;</code></pre>
<pre class="r"><code>unclass(ICPS$SEXE) #A l&#39;enquesta pren els valors d&#39;1 &quot;Home&quot; i 2 &quot;Dona&quot;. Aqui veiem com es distribueixen.</code></pre>
<pre><code>##    [1] 2 2 2 2 2 1 1 2 2 2 1 1 2 1 2 2 1 1 2 2 2 2 1 1 2 1 2 1 2 2 1 2 1 2 1 1 2 2 2
##   [40] 2 1 1 2 1 2 1 1 2 2 2 1 2 2 2 2 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 2 2 1 2 2 2 2 1
##   [79] 2 1 1 2 1 2 2 2 2 2 2 1 1 2 2 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 2 1 1
##  [118] 1 1 2 1 1 1 1 1 2 1 2 1 1 2 1 1 1 1 1 2 1 2 1 1 2 2 1 2 1 2 1 1 2 1 2 2 2 1 2
##  [157] 2 2 2 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 2 2 1 2 1 1 2 1 2 2 1 1 2
##  [196] 2 1 1 2 1 1 1 1 1 1 1 2 1 2 2 2 2 2 1 1 2 1 1 2 2 2 1 2 2 1 1 1 2 2 2 2 1 1 1
##  [235] 2 1 1 1 2 1 2 2 1 2 1 2 1 2 1 2 2 1 2 1 1 2 1 2 2 1 2 1 2 2 2 1 1 2 2 2 2 1 1
##  [274] 1 2 2 2 1 2 2 2 2 2 1 1 1 2 1 1 2 1 2 1 1 2 2 1 1 1 1 2 2 2 1 1 2 1 2 1 1 1 2
##  [313] 1 2 1 2 1 1 2 2 1 2 2 2 1 1 1 1 2 2 2 2 1 2 1 2 1 1 1 1 1 1 1 2 2 2 1 2 1 2 1
##  [352] 1 2 1 1 1 1 1 1 1 1 1 1 1 2 1 1 2 1 1 1 1 2 2 2 1 2 2 2 1 1 2 2 1 1 1 1 1 2 2
##  [391] 1 1 1 1 2 1 1 2 1 1 1 2 2 1 2 1 1 1 1 2 1 2 2 1 2 1 2 1 2 1 1 2 1 2 2 2 1 1 2
##  [430] 2 1 1 1 1 2 2 1 2 2 1 1 2 2 1 2 1 1 2 2 2 2 1 2 1 2 1 1 1 1 2 2 1 1 2 2 2 1 1
##  [469] 2 1 1 2 1 2 2 1 1 2 2 2 1 2 1 1 1 2 1 1 2 2 1 2 2 1 1 2 1 1 1 1 1 1 1 2 1 2 2
##  [508] 1 1 2 2 1 1 2 1 1 2 1 2 1 1 2 1 1 1 1 2 2 2 2 1 1 1 1 1 2 2 2 2 1 1 1 2 2 2 2
##  [547] 1 2 2 1 1 2 1 2 2 1 2 1 1 1 1 1 1 2 1 1 1 2 2 1 1 1 1 2 1 1 1 1 1 1 2 1 2 2 1
##  [586] 1 1 1 2 1 1 1 2 1 2 1 2 1 2 1 2 1 1 2 1 2 2 2 1 1 1 1 1 1 1 2 1 2 1 1 1 1 2 2
##  [625] 2 1 1 1 1 1 1 2 1 1 1 1 1 2 2 2 1 2 2 2 2 1 2 1 2 2 1 1 2 2 2 2 2 1 2 1 2 1 2
##  [664] 1 1 2 1 2 1 2 1 1 1 2 2 2 1 1 2 2 1 1 1 1 2 1 1 1 2 1 2 2 2 2 1 1 1 2 1 1 2 1
##  [703] 1 2 1 2 2 2 1 1 2 2 1 2 1 1 1 2 1 1 2 1 1 2 2 1 1 1 1 1 2 1 1 1 1 2 2 2 1 2 1
##  [742] 2 2 2 1 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1 2 2 2 1 2 2 2 1 2 1 2 2 2 2 2 1 1 2
##  [781] 2 2 2 1 2 1 1 1 1 2 1 1 2 1 1 2 1 1 2 2 2 1 1 2 2 2 1 1 1 1 1 1 1 1 1 2 1 1 2
##  [820] 2 2 1 1 1 2 1 1 2 1 1 1 2 2 2 2 2 1 2 2 1 1 2 2 2 2 2 2 2 2 1 1 2 1 1 1 2 1 1
##  [859] 2 2 1 2 2 2 2 1 2 2 1 2 2 2 1 2 2 2 1 2 1 1 1 1 1 2 2 1 1 1 1 2 1 2 2 2 1 2 2
##  [898] 2 1 1 2 2 1 1 2 2 2 2 1 2 1 2 2 2 1 2 2 1 2 1 1 2 2 2 2 2 2 2 2 1 2 2 1 2 2 2
##  [937] 1 2 1 2 2 2 1 1 2 1 1 1 1 2 1 2 2 2 2 1 1 1 1 2 1 2 2 2 1 2 2 2 2 2 1 1 1 2 2
##  [976] 1 2 1 1 2 2 2 2 2 1 2 1 2 2 1 2 2 1 2 2 2 2 2 1 1
##  [ reached getOption(&quot;max.print&quot;) -- omitted 36972 entries ]
## attr(,&quot;levels&quot;)
## [1] &quot;Home&quot; &quot;Dona&quot;</code></pre>
<pre class="r"><code>glimpse(ICPS$SEXE) #Glimpse ens dona la mateixa informació que les altres funcions però concentrada en un comando. Ens diu que és un factor i que té dos categories: Home i Dona.</code></pre>
<pre><code>##  Factor w/ 2 levels &quot;Home&quot;,&quot;Dona&quot;: 2 2 2 2 2 1 1 2 2 2 ...</code></pre>
<pre class="r"><code>attributes(ICPS$SEXE) #Ens dona la mateixa informació que glimpse()</code></pre>
<pre><code>## $levels
## [1] &quot;Home&quot; &quot;Dona&quot;
## 
## $class
## [1] &quot;factor&quot;</code></pre>
<p>Realitzeu el mateix amb PROVINCIA I HABITAT.</p>
<div id="provincia" class="section level4">
<h4>Provincia</h4>
<pre class="r"><code>glimpse(ICPS$PROVINCIA)</code></pre>
<pre><code>##  Factor w/ 4 levels &quot;Barcelona&quot;,&quot;Girona&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<pre class="r"><code>class(ICPS$PROVINCIA)</code></pre>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<pre class="r"><code>levels(ICPS$PROVINCIA) #Ens dona les categories de la variable en format factor</code></pre>
<pre><code>## [1] &quot;Barcelona&quot; &quot;Girona&quot;    &quot;Lleida&quot;    &quot;Tarragona&quot;</code></pre>
<pre class="r"><code>attributes(ICPS$PROVINCIA)</code></pre>
<pre><code>## $levels
## [1] &quot;Barcelona&quot; &quot;Girona&quot;    &quot;Lleida&quot;    &quot;Tarragona&quot;
## 
## $class
## [1] &quot;factor&quot;</code></pre>
</div>
<div id="dimensió" class="section level4">
<h4>Dimensió</h4>
<pre class="r"><code>glimpse(ICPS$DIMENSIO)</code></pre>
<pre><code>##  Factor w/ 6 levels &quot;Dimensió 1 (Fins a 2.000 hab.)&quot;,..: 6 6 6 6 6 5 5 5 4 4 ...</code></pre>
<pre class="r"><code>class(ICPS$DIMENSIO)</code></pre>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<pre class="r"><code>levels(ICPS$DIMENSIO)</code></pre>
<pre><code>## [1] &quot;Dimensió 1 (Fins a 2.000 hab.)&quot;           
## [2] &quot;Dimensió 2 (De 2.001 a 10.000 hab.)&quot;      
## [3] &quot;Dimensió 3 (De 10.001 a 50.000 hab.)&quot;     
## [4] &quot;Dimensió 4 (De 50.001 a 150.000 hab.)&quot;    
## [5] &quot;Dimensió 5 (De 150.001 a un milió d&#39;hab.)&quot;
## [6] &quot;Dimensió 6 (Més d&#39;un milió d&#39;hab.)&quot;</code></pre>
<pre class="r"><code>attributes(ICPS$DIMENSIO)</code></pre>
<pre><code>## $levels
## [1] &quot;Dimensió 1 (Fins a 2.000 hab.)&quot;           
## [2] &quot;Dimensió 2 (De 2.001 a 10.000 hab.)&quot;      
## [3] &quot;Dimensió 3 (De 10.001 a 50.000 hab.)&quot;     
## [4] &quot;Dimensió 4 (De 50.001 a 150.000 hab.)&quot;    
## [5] &quot;Dimensió 5 (De 150.001 a un milió d&#39;hab.)&quot;
## [6] &quot;Dimensió 6 (Més d&#39;un milió d&#39;hab.)&quot;       
## 
## $class
## [1] &quot;factor&quot;</code></pre>
</div>
<div id="exercici-a-classe-iv.-exercici-a-classe-iv." class="section level4">
<h4>Exercici a classe (IV). Exercici a classe (IV).</h4>
<p>Mireu el llibre de codis de l’enquesta del ICPS (adjunt al material de la sessió) i identifiqueu diferents tipus de variables: quantitatives i qualitatives. Analitzeu-les amb les funcions explicades. Cal que trobeu un variable quantitativa i tres variables qualitatives: nominal, dicotòmica i ordinal.</p>
<p>Recordeu que el codi per carregar la base de dades és aquest.</p>
<p>Aquí teniu el codi per transformar-la en data.frame i veure el nom de les variables.</p>
<pre class="r"><code>ICPS &lt;- as.data.frame(ICPS)
class(ICPS)</code></pre>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p>Nom de les variables:</p>
<pre class="r"><code>names(ICPS)</code></pre>
<pre><code>##   [1] &quot;NUMERO&quot;    &quot;ANY&quot;       &quot;ID01&quot;      &quot;ID02&quot;      &quot;ID03&quot;      &quot;ID11&quot;     
##   [7] &quot;ID12&quot;      &quot;ID13&quot;      &quot;ID14&quot;      &quot;ID15&quot;      &quot;ID21&quot;      &quot;ID22H&quot;    
##  [13] &quot;ID22D&quot;     &quot;ID31&quot;      &quot;ID41&quot;      &quot;IDI&quot;       &quot;V001&quot;      &quot;V002&quot;     
##  [19] &quot;V003&quot;      &quot;V004&quot;      &quot;V005&quot;      &quot;V006&quot;      &quot;V007&quot;      &quot;V008&quot;     
##  [25] &quot;V009&quot;      &quot;V010&quot;      &quot;V011&quot;      &quot;V012&quot;      &quot;V013&quot;      &quot;V014&quot;     
##  [31] &quot;V015&quot;      &quot;V016&quot;      &quot;V017&quot;      &quot;V018&quot;      &quot;V019&quot;      &quot;V020&quot;     
##  [37] &quot;V021&quot;      &quot;V022&quot;      &quot;V023&quot;      &quot;V024&quot;      &quot;V025&quot;      &quot;V026&quot;     
##  [43] &quot;V027&quot;      &quot;V028&quot;      &quot;V029&quot;      &quot;V030&quot;      &quot;V031&quot;      &quot;V032&quot;     
##  [49] &quot;V033&quot;      &quot;V034&quot;      &quot;V035&quot;      &quot;V036&quot;      &quot;V037&quot;      &quot;V038&quot;     
##  [55] &quot;V039&quot;      &quot;V040&quot;      &quot;V041&quot;      &quot;V042&quot;      &quot;V043&quot;      &quot;V044&quot;     
##  [61] &quot;V045&quot;      &quot;V046&quot;      &quot;V047&quot;      &quot;V048&quot;      &quot;V049&quot;      &quot;V050&quot;     
##  [67] &quot;V051&quot;      &quot;V052&quot;      &quot;V053&quot;      &quot;V054&quot;      &quot;V055&quot;      &quot;V056&quot;     
##  [73] &quot;V057&quot;      &quot;V058&quot;      &quot;V059&quot;      &quot;V060&quot;      &quot;V061&quot;      &quot;V062&quot;     
##  [79] &quot;V063&quot;      &quot;V064&quot;      &quot;V065&quot;      &quot;V066&quot;      &quot;V067&quot;      &quot;V068&quot;     
##  [85] &quot;V069&quot;      &quot;V070&quot;      &quot;V071&quot;      &quot;V072&quot;      &quot;V073&quot;      &quot;V074&quot;     
##  [91] &quot;V075&quot;      &quot;V076&quot;      &quot;V077&quot;      &quot;V078&quot;      &quot;V079&quot;      &quot;V080&quot;     
##  [97] &quot;V081&quot;      &quot;V082&quot;      &quot;V083&quot;      &quot;V084&quot;      &quot;V085&quot;      &quot;V086&quot;     
## [103] &quot;V087&quot;      &quot;V088&quot;      &quot;V089&quot;      &quot;V090&quot;      &quot;V091&quot;      &quot;V092&quot;     
## [109] &quot;V093&quot;      &quot;V094&quot;      &quot;V095&quot;      &quot;V096&quot;      &quot;V097&quot;      &quot;V098&quot;     
## [115] &quot;V099&quot;      &quot;V100&quot;      &quot;V101&quot;      &quot;V102&quot;      &quot;V103&quot;      &quot;V104&quot;     
## [121] &quot;V105&quot;      &quot;V106&quot;      &quot;V107&quot;      &quot;V108&quot;      &quot;V109&quot;      &quot;V110&quot;     
## [127] &quot;V111&quot;      &quot;V112&quot;      &quot;V113&quot;      &quot;V114&quot;      &quot;V115&quot;      &quot;V116&quot;     
## [133] &quot;V117&quot;      &quot;V118&quot;      &quot;V119&quot;      &quot;V120&quot;      &quot;V121&quot;      &quot;V122&quot;     
## [139] &quot;V123&quot;      &quot;V124&quot;      &quot;V125&quot;      &quot;V126&quot;      &quot;V127&quot;      &quot;V128&quot;     
## [145] &quot;V129&quot;      &quot;V130&quot;      &quot;V131&quot;      &quot;V132&quot;      &quot;V133&quot;      &quot;V134&quot;     
## [151] &quot;V135&quot;      &quot;V136&quot;      &quot;V137&quot;      &quot;V138&quot;      &quot;V139&quot;      &quot;V140&quot;     
## [157] &quot;V141&quot;      &quot;V142&quot;      &quot;V143&quot;      &quot;V144&quot;      &quot;V145&quot;      &quot;V146&quot;     
## [163] &quot;V147&quot;      &quot;V148&quot;      &quot;V149&quot;      &quot;V150&quot;      &quot;V151&quot;      &quot;V152&quot;     
## [169] &quot;V153&quot;      &quot;V154&quot;      &quot;V155&quot;      &quot;V156&quot;      &quot;V157&quot;      &quot;V158&quot;     
## [175] &quot;V159&quot;      &quot;V160&quot;      &quot;V161&quot;      &quot;V162&quot;      &quot;V163&quot;      &quot;V164&quot;     
## [181] &quot;V165&quot;      &quot;V166&quot;      &quot;V167&quot;      &quot;V168&quot;      &quot;V169&quot;      &quot;V170&quot;     
## [187] &quot;V171&quot;      &quot;V172&quot;      &quot;V173&quot;      &quot;V174&quot;      &quot;V175&quot;      &quot;V176&quot;     
## [193] &quot;V177&quot;      &quot;V178&quot;      &quot;V179&quot;      &quot;V180&quot;      &quot;V181&quot;      &quot;V182&quot;     
## [199] &quot;V183&quot;      &quot;V184&quot;      &quot;V185&quot;      &quot;V186&quot;      &quot;V187&quot;      &quot;V188&quot;     
## [205] &quot;V189&quot;      &quot;V190&quot;      &quot;V191&quot;      &quot;V192&quot;      &quot;V193&quot;      &quot;V194&quot;     
## [211] &quot;V195&quot;      &quot;V196&quot;      &quot;V197&quot;      &quot;V198&quot;      &quot;V199&quot;      &quot;V200&quot;     
## [217] &quot;V201&quot;      &quot;V202&quot;      &quot;V203&quot;      &quot;V204&quot;      &quot;V205&quot;      &quot;V206&quot;     
## [223] &quot;V207&quot;      &quot;V208&quot;      &quot;V209&quot;      &quot;V210&quot;      &quot;V211&quot;      &quot;V212&quot;     
## [229] &quot;V213&quot;      &quot;V214&quot;      &quot;V215&quot;      &quot;V216&quot;      &quot;V217&quot;      &quot;V218&quot;     
## [235] &quot;V219&quot;      &quot;V220&quot;      &quot;V221&quot;      &quot;V222&quot;      &quot;V223&quot;      &quot;V224&quot;     
## [241] &quot;V225&quot;      &quot;V226&quot;      &quot;V227&quot;      &quot;V228&quot;      &quot;V229&quot;      &quot;V230&quot;     
## [247] &quot;V231&quot;      &quot;V232&quot;      &quot;V233&quot;      &quot;V234&quot;      &quot;V235&quot;      &quot;V236&quot;     
## [253] &quot;V237&quot;      &quot;V238&quot;      &quot;V239&quot;      &quot;V240&quot;      &quot;V241&quot;      &quot;V242&quot;     
## [259] &quot;V243&quot;      &quot;V244&quot;      &quot;V245&quot;      &quot;V246&quot;      &quot;V247&quot;      &quot;V248&quot;     
## [265] &quot;V249&quot;      &quot;V250&quot;      &quot;V251&quot;      &quot;V252&quot;      &quot;V253&quot;      &quot;V254&quot;     
## [271] &quot;V255&quot;      &quot;V256&quot;      &quot;V257&quot;      &quot;V258&quot;      &quot;V259&quot;      &quot;V260&quot;     
## [277] &quot;V261&quot;      &quot;V262&quot;      &quot;V263&quot;      &quot;V264&quot;      &quot;V265&quot;      &quot;V266&quot;     
## [283] &quot;V267&quot;      &quot;V268&quot;      &quot;V269&quot;      &quot;V270&quot;      &quot;V271&quot;      &quot;V272&quot;     
## [289] &quot;V273&quot;      &quot;V274&quot;      &quot;V275&quot;      &quot;V276&quot;      &quot;V277&quot;      &quot;V278&quot;     
## [295] &quot;V279&quot;      &quot;V280&quot;      &quot;V281&quot;      &quot;V282&quot;      &quot;V283&quot;      &quot;V284&quot;     
## [301] &quot;V285&quot;      &quot;V286&quot;      &quot;V287&quot;      &quot;V288&quot;      &quot;V289&quot;      &quot;V290&quot;     
## [307] &quot;V291&quot;      &quot;V292&quot;      &quot;V293&quot;      &quot;V294&quot;      &quot;V295&quot;      &quot;V296&quot;     
## [313] &quot;V297&quot;      &quot;V298&quot;      &quot;V299&quot;      &quot;V300&quot;      &quot;V301&quot;      &quot;V302&quot;     
## [319] &quot;V303&quot;      &quot;V304&quot;      &quot;V305&quot;      &quot;V306&quot;      &quot;V307&quot;      &quot;V308&quot;     
## [325] &quot;V309&quot;      &quot;V310&quot;      &quot;V311&quot;      &quot;V312&quot;      &quot;V313&quot;      &quot;V314&quot;     
## [331] &quot;V315&quot;      &quot;V316&quot;      &quot;V317&quot;      &quot;V318&quot;      &quot;V319&quot;      &quot;V320&quot;     
## [337] &quot;V321&quot;      &quot;V322&quot;      &quot;V323&quot;      &quot;V324&quot;      &quot;V325&quot;      &quot;V326&quot;     
## [343] &quot;V327&quot;      &quot;V328&quot;      &quot;V329&quot;      &quot;V330&quot;      &quot;V331&quot;      &quot;V332&quot;     
## [349] &quot;V333&quot;      &quot;V334&quot;      &quot;V335&quot;      &quot;V336&quot;      &quot;V337&quot;      &quot;V338&quot;     
## [355] &quot;V339&quot;      &quot;V340&quot;      &quot;V341&quot;      &quot;V342&quot;      &quot;V343&quot;      &quot;V344&quot;     
## [361] &quot;V345&quot;      &quot;V346&quot;      &quot;V347&quot;      &quot;V348&quot;      &quot;V349&quot;      &quot;V350&quot;     
## [367] &quot;V351&quot;      &quot;V352&quot;      &quot;v352_2&quot;    &quot;V353&quot;      &quot;v353_2&quot;    &quot;V354&quot;     
## [373] &quot;v354_2&quot;    &quot;V355&quot;      &quot;V356&quot;      &quot;V357&quot;      &quot;V358&quot;      &quot;V359&quot;     
## [379] &quot;V360&quot;      &quot;V361&quot;      &quot;V362&quot;      &quot;V363&quot;      &quot;V364&quot;      &quot;V365&quot;     
## [385] &quot;V366&quot;      &quot;V367&quot;      &quot;V368&quot;      &quot;V369&quot;      &quot;V370&quot;      &quot;V371&quot;     
## [391] &quot;V372&quot;      &quot;V373&quot;      &quot;V374&quot;      &quot;V375&quot;      &quot;V376&quot;      &quot;V377&quot;     
## [397] &quot;V378&quot;      &quot;V379&quot;      &quot;V380&quot;      &quot;V381&quot;      &quot;V382&quot;      &quot;V383&quot;     
## [403] &quot;V384&quot;      &quot;V385&quot;      &quot;V386&quot;      &quot;V387&quot;      &quot;V388&quot;      &quot;V389&quot;     
## [409] &quot;V390&quot;      &quot;V391&quot;      &quot;V392&quot;      &quot;V393&quot;      &quot;V394&quot;      &quot;V395&quot;     
## [415] &quot;V396&quot;      &quot;V397&quot;      &quot;V398&quot;      &quot;V399&quot;      &quot;V400&quot;      &quot;V401&quot;     
## [421] &quot;V402&quot;      &quot;V403&quot;      &quot;V404&quot;      &quot;V405&quot;      &quot;V406&quot;      &quot;V407&quot;     
## [427] &quot;V408&quot;      &quot;V409&quot;      &quot;V410&quot;      &quot;V411&quot;      &quot;V412&quot;      &quot;V413&quot;     
## [433] &quot;V414&quot;      &quot;V415&quot;      &quot;V416&quot;      &quot;V417&quot;      &quot;V418&quot;      &quot;V419&quot;     
## [439] &quot;V420&quot;      &quot;V421&quot;      &quot;V422&quot;      &quot;V423&quot;      &quot;V424&quot;      &quot;V425&quot;     
## [445] &quot;V426&quot;      &quot;V427&quot;      &quot;V428&quot;      &quot;V429&quot;      &quot;V430&quot;      &quot;V431&quot;     
## [451] &quot;V432&quot;      &quot;V433&quot;      &quot;V434&quot;      &quot;V435&quot;      &quot;V436&quot;      &quot;V437&quot;     
## [457] &quot;V438&quot;      &quot;V439&quot;      &quot;V440&quot;      &quot;V441&quot;      &quot;V442&quot;      &quot;V443&quot;     
## [463] &quot;V444&quot;      &quot;V445&quot;      &quot;V446&quot;      &quot;V447&quot;      &quot;V448&quot;      &quot;V449&quot;     
## [469] &quot;V450&quot;      &quot;V451&quot;      &quot;V452&quot;      &quot;V453&quot;      &quot;V454&quot;      &quot;V455&quot;     
## [475] &quot;V456&quot;      &quot;V457&quot;      &quot;V458&quot;      &quot;V459&quot;      &quot;V460&quot;      &quot;V461&quot;     
## [481] &quot;V462&quot;      &quot;V463&quot;      &quot;V464&quot;      &quot;V465&quot;      &quot;V466&quot;      &quot;V467&quot;     
## [487] &quot;V468&quot;      &quot;V469&quot;      &quot;V470&quot;      &quot;V471&quot;      &quot;V472&quot;      &quot;V473&quot;     
## [493] &quot;V474&quot;      &quot;V475&quot;      &quot;V476&quot;      &quot;V477&quot;      &quot;V478&quot;      &quot;V479&quot;     
## [499] &quot;V480&quot;      &quot;V481&quot;      &quot;V482&quot;      &quot;V483&quot;      &quot;V484&quot;      &quot;V485&quot;     
## [505] &quot;V486&quot;      &quot;V487&quot;      &quot;V488&quot;      &quot;V489&quot;      &quot;V490&quot;      &quot;V491&quot;     
## [511] &quot;V492&quot;      &quot;V493&quot;      &quot;V494&quot;      &quot;V495&quot;      &quot;V496&quot;      &quot;V497&quot;     
## [517] &quot;V498&quot;      &quot;V499&quot;      &quot;V500&quot;      &quot;V501&quot;      &quot;V502&quot;      &quot;V503&quot;     
## [523] &quot;SEXE&quot;      &quot;EDAT&quot;      &quot;V504&quot;      &quot;V505&quot;      &quot;V506&quot;      &quot;V507&quot;     
## [529] &quot;V508&quot;      &quot;V509&quot;      &quot;V510&quot;      &quot;V511&quot;      &quot;V512&quot;      &quot;V513&quot;     
## [535] &quot;V514&quot;      &quot;V515&quot;      &quot;V516&quot;      &quot;V517&quot;      &quot;V518&quot;      &quot;V519&quot;     
## [541] &quot;V520&quot;      &quot;V521&quot;      &quot;V522&quot;      &quot;V523&quot;      &quot;V524&quot;      &quot;V525&quot;     
## [547] &quot;V526&quot;      &quot;V527&quot;      &quot;V528&quot;      &quot;V529&quot;      &quot;V530&quot;      &quot;V531&quot;     
## [553] &quot;V532&quot;      &quot;V533&quot;      &quot;V534&quot;      &quot;V535&quot;      &quot;V536&quot;      &quot;V537&quot;     
## [559] &quot;V538&quot;      &quot;V539&quot;      &quot;V540&quot;      &quot;V541&quot;      &quot;V542&quot;      &quot;V543&quot;     
## [565] &quot;V544&quot;      &quot;V545&quot;      &quot;V546&quot;      &quot;V547&quot;      &quot;V548&quot;      &quot;PROVINCIA&quot;
## [571] &quot;DIMENSIO&quot;  &quot;DISTRICTE&quot; &quot;PES&quot;</code></pre>
</div>
</div>
<div id="recodificació-de-variables-en-r." class="section level3">
<h3>Recodificació de variables en R.</h3>
<p>La recodificació de variables és la transformació d’un determinat tipus de variable en una d’un tipus diferent. Comencem creant una nova base de dades,</p>
<p>• Creem dos vector amb informació: un caràcter i un vector numèric:</p>
<pre class="r"><code>country &lt;- c(&quot;Armenia&quot;, &quot;Austria&quot;,&quot;Benin&quot;,&quot;Bolivia&quot;,&quot;Brasil&quot;,&quot;Colombia&quot;,&quot;El Salvador&quot;,
             &quot;Etiopia&quot;,&quot;Honduras&quot;,&quot;Indonesia&quot;)
class(country) #Ens dona informació sobre que és un caràcter (variable qualitativa nominal)</code></pre>
<pre><code>## [1] &quot;character&quot;</code></pre>
<pre class="r"><code>poverty &lt;- c(1.90,0.7,49.6,6.4,3.4,4.5,1.9,26.7,16.2,7.2)

class(poverty) #Ens diu que és un vector numèric (variable quantitativa continua)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre class="r"><code>unemployment &lt;- c(13.5, 5.2, 45.4,25.6,17.8,21.3,63.4,44.3,52.3,10.4)

class(unemployment)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre class="r"><code>population &lt;- c(3001643, 8935112, 12114193, 11633371, 212216052, 51049498, 6704121, 98665000, 9368926, 259903244)

class(population)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre class="r"><code>gini &lt;- c(34.4, 29.7, 47.8, 42.2, 53.9, 50.4, 38.6, 35.0, 52.1, 37.8)

class(gini)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre class="r"><code>pibcap &lt;- c(4732,50552,1259,2579,11121,7838,3572,602,2241,4450)

class(pibcap)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>Totes les dades s’han extret de la pàgina web del Banc Mundial. Execepte la primer, tota la resta de variables son numèriques.</p>
<p>• Creem la base de dades unint els dos vectors amb la funció data.frame():</p>
<pre class="r"><code>pov &lt;- data.frame(country, poverty, unemployment, population, gini, pibcap)
#View(pov) #Visualitzem la taula.
class(pov) #Ens diu que es un data.frame.</code></pre>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<pre class="r"><code>glimpse(pov) #Ens diu que tenim un data.frame amb 10 fileres i dos columnes de variables una en format caràcter i l&#39;altra numèric.</code></pre>
<pre><code>## Rows: 10
## Columns: 6
## $ country      &lt;chr&gt; &quot;Armenia&quot;, &quot;Austria&quot;, &quot;Benin&quot;, &quot;Bolivia&quot;, &quot;Brasil&quot;, &quot;Colombia~
## $ poverty      &lt;dbl&gt; 1.9, 0.7, 49.6, 6.4, 3.4, 4.5, 1.9, 26.7, 16.2, 7.2
## $ unemployment &lt;dbl&gt; 13.5, 5.2, 45.4, 25.6, 17.8, 21.3, 63.4, 44.3, 52.3, 10.4
## $ population   &lt;dbl&gt; 3001643, 8935112, 12114193, 11633371, 212216052, 51049498, 67~
## $ gini         &lt;dbl&gt; 34.4, 29.7, 47.8, 42.2, 53.9, 50.4, 38.6, 35.0, 52.1, 37.8
## $ pibcap       &lt;dbl&gt; 4732, 50552, 1259, 2579, 11121, 7838, 3572, 602, 2241, 4450</code></pre>
<p>Existeixen diversos tipus de recodificació de variables. Tanmateix, cal fer dos passos previament:</p>
<ol style="list-style-type: decimal">
<li>Carregar la llibreria tidyverse.</li>
<li>Quan recodifiquem variables és útil posar algun distintiu en el nom de la nova variable que ens recordi que ha estat recodificada. L’ús d’una _R al final o del sufix _rec ens pot ajudar.</li>
</ol>
<div id="recodificar-variables-continues-a-categòriques-i-el-mètode-if_elfe" class="section level4">
<h4>1. Recodificar variables continues a categòriques I: el mètode if_elfe()</h4>
<p>Carreguem en primer lloc la llibreria tidyverse.</p>
<pre class="r"><code>library(tidyverse)</code></pre>
<p>A partir d’ara, començarem Seleccionem el nom de la variable que volem recodificar passant-la de numèrica a qualitativa i apliquem la funció if_else().</p>
<pre class="r"><code>pov$unemployment_rec &lt;- if_else(pov$unemployment &gt;= 25, &quot;Alt&quot;, &quot;Baix&quot;)

summary(pov$unemployment)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    5.20   14.57   23.45   29.92   45.12   63.40</code></pre>
<pre class="r"><code>pov$unemployment_rec2 &lt;- if_else(pov$unemployment &gt;= mean(pov$unemployment), &quot;Per sobre mitjana&quot;, &quot;Per sota mitjana&quot;)

table(pov$unemployment_rec2)</code></pre>
<pre><code>## 
## Per sobre mitjana  Per sota mitjana 
##                 4                 6</code></pre>
<p>Amb la funció if_else hem dit que tots aquells casos que la seva taxa d’atur sigui major de 25% (més gran o igual que). Es nomenaran a partir d’ara “Alt” i que els restans seran “Baix”. El resultat és el següent:</p>
<pre class="r"><code>View(pov$unemployment_rec) #Mirem com ha quedat la nova base de dades amb la recodificació feta.
table(pov$unemployment_rec)</code></pre>
<pre><code>## 
##  Alt Baix 
##    5    5</code></pre>
</div>
<div id="recodificar-variables-continues-a-categòriques-ii-el-mètode-case_when" class="section level4">
<h4>2. Recodificar variables continues a categòriques II: el mètode case_when()</h4>
<p>Seleccionem el nom de la variable que volem recodificar passant-la de numèrica a qualitativa. En aquest cas volem transformar la variable pov$poverty que és numèrica continua en una qualitativa ordinal amb tres categories: “Low”,“Medium”,“High”.</p>
<pre class="r"><code>summary(pov$poverty)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.700   2.275   5.450  11.850  13.950  49.600</code></pre>
<pre class="r"><code>pov$poverty_rec &lt;- case_when(pov$poverty &lt; 10 ~ &quot;Low&quot;, between(pov$population, 10, 15) ~ &quot;Medium&quot;, TRUE ~ &quot;High&quot;)</code></pre>
<p>Ens ha transformat la variable poverty en una variable qualitativa ordinal que cal ordenar amb la següent funció.</p>
<pre class="r"><code>pov$poverty_rec &lt;- factor(pov$poverty_rec, order = TRUE, levels = c(&quot;Low&quot;, &quot;Medium&quot;,&quot;High&quot;))
class(pov$poverty_rec) #Si mirem amb la funció class() ja ens diu que tenim una variable qualitativa ordinal (ordered factor)</code></pre>
<pre><code>## [1] &quot;ordered&quot; &quot;factor&quot;</code></pre>
<pre class="r"><code>table(pov$poverty_rec)</code></pre>
<pre><code>## 
##    Low Medium   High 
##      7      0      3</code></pre>
<p>En aquest cas transformarem la variable numèrica population en una de qualitativa ordinal també per mitjà de la funció case_when().</p>
<pre class="r"><code>pov$population_rec &lt;- case_when(pov$population &lt; 10000000 ~ &quot;Low size&quot;, between(pov$population, 10000001, 60000000) ~ &quot;Medium Size&quot;, TRUE ~ &quot;Big Size&quot;)
View(pov$population_rec)
table(pov$population_rec)</code></pre>
<pre><code>## 
##    Big Size    Low size Medium Size 
##           3           4           3</code></pre>
</div>
<div id="recodificació-de-variables-continues-a-categòriques-iii-el-mètode-cut." class="section level4">
<h4>3. Recodificació de variables continues a categòriques III: el mètode cut.</h4>
<p>Recodifiquem amb la funció cut(). Aquesta funció és útil per trencar en parts iguals variables numèriques.</p>
<pre class="r"><code>pov$gini_rec &lt;-cut(pov$gini, breaks = 3) #Especifiquem el nombre de talls amb l&#39;argument breaks.
table(pov$gini_rec) #observem la nova distribució de casos amb les noves categories.</code></pre>
<pre><code>## 
## (29.7,37.8] (37.8,45.8] (45.8,53.9] 
##           3           3           4</code></pre>
<p>Tanmateix, aquestes noves categories que son intervals numèrics no ens diuen res i necessitem posar-li un nom.</p>
<pre class="r"><code>pov$gini_rec &lt;-cut(pov$gini, breaks = 3, labels = c(&quot;Nivell baix desigualtat&quot;, &quot;Nivell mig desigualtat&quot;, &quot;Nivell alt desigualtat&quot;))
as.factor(pov$gini_rec)</code></pre>
<pre><code>##  [1] Nivell baix desigualtat Nivell baix desigualtat Nivell alt desigualtat 
##  [4] Nivell mig desigualtat  Nivell alt desigualtat  Nivell alt desigualtat 
##  [7] Nivell mig desigualtat  Nivell baix desigualtat Nivell alt desigualtat 
## [10] Nivell mig desigualtat 
## 3 Levels: Nivell baix desigualtat ... Nivell alt desigualtat</code></pre>
<pre class="r"><code>table(pov$gini_rec)</code></pre>
<pre><code>## 
## Nivell baix desigualtat  Nivell mig desigualtat  Nivell alt desigualtat 
##                       3                       3                       4</code></pre>
<p>Repetim el procés amb la variable pibcap.</p>
<pre class="r"><code>pov$pibcap_rec &lt;-cut(pov$pibcap, breaks = 3, labels = c(&quot;Baix&quot;, &quot;Mig&quot;, &quot;Alt&quot;))
as.factor(pov$pibcap_rec)</code></pre>
<pre><code>##  [1] Baix Alt  Baix Baix Baix Baix Baix Baix Baix Baix
## Levels: Baix Mig Alt</code></pre>
<pre class="r"><code>table(pov$pibcap_rec)</code></pre>
<pre><code>## 
## Baix  Mig  Alt 
##    9    0    1</code></pre>
<p>També podem fixar els talls nosaltres creant un vector numéric. Ho farem seguint els talls que ens doni summary(). La funció summary() ens resumeix alguns dels estadístics descriptius de la variable numèrica que analitzem.</p>
<pre class="r"><code>summary(pov$unemployment)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    5.20   14.57   23.45   29.92   45.12   63.40</code></pre>
<p>En aquest cas ens dona el primer quartil, la mediana i la mitjana. Marquem els talls: de 0 a 15, de 15 a 30, de 30 a 45, de 45 a 60 i més de 60)</p>
<pre class="r"><code>pov$unemployment_rec3 &lt;-cut(pov$unemployment, breaks = c(0,15,30,45,60))
table(pov$unemployment_rec3)</code></pre>
<pre><code>## 
##  (0,15] (15,30] (30,45] (45,60] 
##       3       3       1       2</code></pre>
<p>Tornem a recodificar amb la base de dades sobre qualitat democràtica de la Freedom House que hem carregat abans. Recodifiquem amb if_else() i amb case_when().</p>
</div>
<div id="més-exemples-de-recodificació-de-variables.-ús-de-la-funció-recode" class="section level4">
<h4>4. Més exemples de recodificació de variables. Ús de la funció recode()</h4>
<div id="exemple-i." class="section level5">
<h5>Exemple I.</h5>
<pre class="r"><code>#glimpse(ICPS)</code></pre>
<p>Busquem una variable ordinal que podem dicotomitzar, és a dir, que la podem transformar en una variable amb únicament dues opcions.</p>
<p>Trobem la variable V010 Qualificació de l’actual situació política a Catalunya. Aquesta variable recull l’opinió dels enquestats sobre la situació política catalana.</p>
<pre class="r"><code>class(ICPS$V010) #És un factor.</code></pre>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<pre class="r"><code>levels(ICPS$V010) #Té quatre nivells de resposta ordenats: és una variable qualitativa ordinal.</code></pre>
<pre><code>## [1] &quot;Molt bona&quot;    &quot;Bona&quot;         &quot;Regular&quot;      &quot;Dolenta&quot;      &quot;Molt dolenta&quot;
## [6] &quot;No sap&quot;       &quot;No contesta&quot;</code></pre>
<pre class="r"><code>attributes(ICPS$V010) #Confirmem els nivells i el tipus d&#39;objecte que és.</code></pre>
<pre><code>## $levels
## [1] &quot;Molt bona&quot;    &quot;Bona&quot;         &quot;Regular&quot;      &quot;Dolenta&quot;      &quot;Molt dolenta&quot;
## [6] &quot;No sap&quot;       &quot;No contesta&quot; 
## 
## $class
## [1] &quot;factor&quot;</code></pre>
<pre class="r"><code>glimpse(ICPS$V010)</code></pre>
<pre><code>##  Factor w/ 7 levels &quot;Molt bona&quot;,&quot;Bona&quot;,..: NA NA NA NA NA NA NA NA NA NA ...</code></pre>
<p>Recodifiquem en una variable dicotòmica que només tingui dues opcions: Negativa i Positiva.</p>
<pre class="r"><code>ICPS$V010R &lt;- recode(ICPS$V010, &quot;Molt bona&quot; = &quot;Positiva&quot;, &quot;Bona&quot; = &quot;Positiva&quot;, &quot;Dolenta&quot; = &quot;Negativa&quot;, &quot;Molt dolenta&quot; = &quot;Negativa&quot;, .default = NA_character_)</code></pre>
<p>Li diem ICPS$V010R per mantenir les dades originals sense manipular. Al afegir la R creem una altra variablr nova.</p>
<pre class="r"><code>glimpse(ICPS$V010R)</code></pre>
<pre><code>##  Factor w/ 2 levels &quot;Positiva&quot;,&quot;Negativa&quot;: NA NA NA NA NA NA NA NA NA NA ...</code></pre>
<pre class="r"><code>table(ICPS$V010R)</code></pre>
<pre><code>## 
## Positiva Negativa 
##     5487     8368</code></pre>
<p>Hem convertit les categories “Molt bona” i “Bona” en “Positiva” i “Molt dolenta” i “Dolenta” en “Negativa”. Això el que ha fet es agrupar els casos de 4 opcions a 2. També hem eliminat la resta de valors (Regular, NS i NC).</p>
</div>
<div id="exemple-ii." class="section level5">
<h5>Exemple II.</h5>
<p>Provem de nou. Ara amb la variable V182 vinculada a les relacions entre Catalunya i Espanya. La variable dona fins a quatre opcions sobre el que Catalunya hauria de ser respecte a Espanya.</p>
<pre class="r"><code>class(ICPS$V182)</code></pre>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<pre class="r"><code>levels(ICPS$V182)</code></pre>
<pre><code>## [1] &quot;Una regió d&#39;Espanya&quot;              &quot;Una Comunitat Autònoma d&#39;Espanya&quot;
## [3] &quot;Un Estat d&#39;una Espanya Federal&quot;   &quot;Un Estat independent&quot;            
## [5] &quot;Altres&quot;                           &quot;No sap&quot;                          
## [7] &quot;No contesta&quot;</code></pre>
<pre class="r"><code>attributes(ICPS$V182)</code></pre>
<pre><code>## $levels
## [1] &quot;Una regió d&#39;Espanya&quot;              &quot;Una Comunitat Autònoma d&#39;Espanya&quot;
## [3] &quot;Un Estat d&#39;una Espanya Federal&quot;   &quot;Un Estat independent&quot;            
## [5] &quot;Altres&quot;                           &quot;No sap&quot;                          
## [7] &quot;No contesta&quot;                     
## 
## $class
## [1] &quot;factor&quot;</code></pre>
<pre class="r"><code>glimpse(ICPS$V182)</code></pre>
<pre><code>##  Factor w/ 7 levels &quot;Una regió d&#39;Espanya&quot;,..: 2 1 2 2 2 1 1 2 2 3 ...</code></pre>
<p>Veiem com es distribueixen els casos en aquestes categories:</p>
<pre class="r"><code>table(ICPS$V182)</code></pre>
<pre><code>## 
##              Una regió d&#39;Espanya Una Comunitat Autònoma d&#39;Espanya 
##                             3487                            17499 
##   Un Estat d&#39;una Espanya Federal             Un Estat independent 
##                             6330                             8579 
##                           Altres                           No sap 
##                              243                             1672 
##                      No contesta 
##                              162</code></pre>
<p>Recodifiquem en dos categories: “Romandre a Espanya” i “Independència”.</p>
<pre class="r"><code>ICPS$V182R &lt;- recode(ICPS$V182, &quot;Una regió d&#39;Espanya&quot; = &quot;Romandre a Espanya&quot;, &quot;Una Comunitat Autònoma d&#39;Espanya&quot; = &quot;Romandre a Espanya&quot;, &quot;Un Estat d&#39;una Espanya Federal&quot; = &quot;Romandre a Espanya&quot;, &quot;Un Estat independent&quot; = &quot;Independència&quot;, .default = NA_character_)
class(ICPS$V182R)</code></pre>
<pre><code>## [1] &quot;factor&quot;</code></pre>
<pre class="r"><code>levels(ICPS$V182R)</code></pre>
<pre><code>## [1] &quot;Romandre a Espanya&quot; &quot;Independència&quot;</code></pre>
<pre class="r"><code>glimpse(ICPS$V182R)</code></pre>
<pre><code>##  Factor w/ 2 levels &quot;Romandre a Espanya&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
<pre class="r"><code>table(ICPS$V182R)</code></pre>
<pre><code>## 
## Romandre a Espanya      Independència 
##              27316               8579</code></pre>
<p>És important entendre quina és la funció de recodificar i quins objectius perseguim amb això.</p>
</div>
</div>
</div>
<div id="exploració-ordenació-i-transformació-de-bases-de-dades-amb-dplyr-y-el-paquet-tidyverse" class="section level3">
<h3>Exploració, ordenació i transformació de bases de dades amb dplyr y el paquet tidyverse</h3>
<p>Dedicarem aquest apartat a endreçar (tidy) les bases de dades per operar millor amb elles.</p>
<p>• Carreguem primer les llibreries que utilitzarem i després les dades.</p>
<pre class="r"><code>library(tidyverse)
library(dplyr)</code></pre>
<p>• Carreguem ara una base de dades del sistema.</p>
<pre class="r"><code>#install.packages(&quot;gapminder&quot;)
library(gapminder)</code></pre>
<pre><code>## Warning: package &#39;gapminder&#39; was built under R version 4.0.4</code></pre>
<div id="exploració-general-dun-data.frame" class="section level4">
<h4>Exploració general d’un data.frame</h4>
<p>Obrim la base de dades com un tibble():</p>
<pre class="r"><code>gapminder</code></pre>
<pre><code>## # A tibble: 1,704 x 6
##    country     continent  year lifeExp      pop gdpPercap
##    &lt;fct&gt;       &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;
##  1 Afghanistan Asia       1952    28.8  8425333      779.
##  2 Afghanistan Asia       1957    30.3  9240934      821.
##  3 Afghanistan Asia       1962    32.0 10267083      853.
##  4 Afghanistan Asia       1967    34.0 11537966      836.
##  5 Afghanistan Asia       1972    36.1 13079460      740.
##  6 Afghanistan Asia       1977    38.4 14880372      786.
##  7 Afghanistan Asia       1982    39.9 12881816      978.
##  8 Afghanistan Asia       1987    40.8 13867957      852.
##  9 Afghanistan Asia       1992    41.7 16317921      649.
## 10 Afghanistan Asia       1997    41.8 22227415      635.
## # ... with 1,694 more rows</code></pre>
<pre class="r"><code>as.tibble(gapminder)</code></pre>
<pre><code>## Warning: `as.tibble()` was deprecated in tibble 2.0.0.
## Please use `as_tibble()` instead.
## The signature and semantics have changed, see `?as_tibble`.</code></pre>
<pre><code>## # A tibble: 1,704 x 6
##    country     continent  year lifeExp      pop gdpPercap
##    &lt;fct&gt;       &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;
##  1 Afghanistan Asia       1952    28.8  8425333      779.
##  2 Afghanistan Asia       1957    30.3  9240934      821.
##  3 Afghanistan Asia       1962    32.0 10267083      853.
##  4 Afghanistan Asia       1967    34.0 11537966      836.
##  5 Afghanistan Asia       1972    36.1 13079460      740.
##  6 Afghanistan Asia       1977    38.4 14880372      786.
##  7 Afghanistan Asia       1982    39.9 12881816      978.
##  8 Afghanistan Asia       1987    40.8 13867957      852.
##  9 Afghanistan Asia       1992    41.7 16317921      649.
## 10 Afghanistan Asia       1997    41.8 22227415      635.
## # ... with 1,694 more rows</code></pre>
<p>Observem és un data.frame que té 1.704 observacions o casos (files) i 6 variables (columna). A més, també ens informa de la tipologia de variables que tenim:</p>
<p>• 2 son qualitatives en format factor: country i continent. • 4 variables quantitatives: 2 continues que son double o numeric (lifeExp and gdpPercap) i dues discretes amb formast integer (year and pop)</p>
<p>Amb les funcions head() i tail() podem observasr els 6 primers casos i els 6 últims.</p>
<pre class="r"><code>head(gapminder) #### Ens ensenya els 6 primers casos o files.</code></pre>
<pre><code>## # A tibble: 6 x 6
##   country     continent  year lifeExp      pop gdpPercap
##   &lt;fct&gt;       &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;
## 1 Afghanistan Asia       1952    28.8  8425333      779.
## 2 Afghanistan Asia       1957    30.3  9240934      821.
## 3 Afghanistan Asia       1962    32.0 10267083      853.
## 4 Afghanistan Asia       1967    34.0 11537966      836.
## 5 Afghanistan Asia       1972    36.1 13079460      740.
## 6 Afghanistan Asia       1977    38.4 14880372      786.</code></pre>
<pre class="r"><code>tail(gapminder) #### Ens ensenya les 6 darreres files.</code></pre>
<pre><code>## # A tibble: 6 x 6
##   country  continent  year lifeExp      pop gdpPercap
##   &lt;fct&gt;    &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;
## 1 Zimbabwe Africa     1982    60.4  7636524      789.
## 2 Zimbabwe Africa     1987    62.4  9216418      706.
## 3 Zimbabwe Africa     1992    60.4 10704340      693.
## 4 Zimbabwe Africa     1997    46.8 11404948      792.
## 5 Zimbabwe Africa     2002    40.0 11926563      672.
## 6 Zimbabwe Africa     2007    43.5 12311143      470.</code></pre>
<p>La funció names() ens mostra el nom de les variables que tenim en aquest data.frame.</p>
<pre class="r"><code>names(gapminder)</code></pre>
<pre><code>## [1] &quot;country&quot;   &quot;continent&quot; &quot;year&quot;      &quot;lifeExp&quot;   &quot;pop&quot;       &quot;gdpPercap&quot;</code></pre>
<p>Si volem saber el nom d’una o varies columnes en qüestió:</p>
<pre class="r"><code>names(gapminder)[2] ### Ens donarà el nom de la segona columna del data.frame.</code></pre>
<pre><code>## [1] &quot;continent&quot;</code></pre>
<pre class="r"><code>names(gapminder)[2:4] ### Ens donarà el nom de les columnes de la 2 a la 4.</code></pre>
<pre><code>## [1] &quot;continent&quot; &quot;year&quot;      &quot;lifeExp&quot;</code></pre>
<p>Si volem extreure tota la informació d’un determinada variable hem d’aplicar els corxetes.</p>
<pre class="r"><code>gapminder[,4] #Ens dona tots els valors de la variable 4 (lifeExp)</code></pre>
<pre><code>## # A tibble: 1,704 x 1
##    lifeExp
##      &lt;dbl&gt;
##  1    28.8
##  2    30.3
##  3    32.0
##  4    34.0
##  5    36.1
##  6    38.4
##  7    39.9
##  8    40.8
##  9    41.7
## 10    41.8
## # ... with 1,694 more rows</code></pre>
<p>Sí el que volem es veure un determinat cas o observació:</p>
<pre class="r"><code>gapminder[15,] #Ens dona tota la informació de la fila 15: el valor a cada variable.</code></pre>
<pre><code>## # A tibble: 1 x 6
##   country continent  year lifeExp     pop gdpPercap
##   &lt;fct&gt;   &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;   &lt;int&gt;     &lt;dbl&gt;
## 1 Albania Europe     1962    64.8 1728137     2313.</code></pre>
<p>També podem utilitzar funcions com str() i glimpse() que son més generalistes.</p>
<pre class="r"><code>str(gapminder) #### Ens dona info de la base de dades (casos i variables) i info de totes les variables.</code></pre>
<pre><code>## tibble [1,704 x 6] (S3: tbl_df/tbl/data.frame)
##  $ country  : Factor w/ 142 levels &quot;Afghanistan&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ continent: Factor w/ 5 levels &quot;Africa&quot;,&quot;Americas&quot;,..: 3 3 3 3 3 3 3 3 3 3 ...
##  $ year     : int [1:1704] 1952 1957 1962 1967 1972 1977 1982 1987 1992 1997 ...
##  $ lifeExp  : num [1:1704] 28.8 30.3 32 34 36.1 ...
##  $ pop      : int [1:1704] 8425333 9240934 10267083 11537966 13079460 14880372 12881816 13867957 16317921 22227415 ...
##  $ gdpPercap: num [1:1704] 779 821 853 836 740 ...</code></pre>
<pre class="r"><code>#glimpse(gapminder) #### Ens dona la mateixa informació en format tibble()</code></pre>
</div>
<div id="exploració-específica-dels-casos-i-variables-dun-data.frame" class="section level4">
<h4>Exploració específica dels casos i variables d’un data.frame</h4>
<p>Analitzem ara una variable.</p>
<pre class="r"><code>#gapminder$country</code></pre>
<p>Ens surt a la consola el nom de totes les etiquetes (142) i com es distribueixen.</p>
<pre class="r"><code>unique(gapminder$country) #### Els països de la base de dades.</code></pre>
<pre><code>##   [1] Afghanistan              Albania                  Algeria                 
##   [4] Angola                   Argentina                Australia               
##   [7] Austria                  Bahrain                  Bangladesh              
##  [10] Belgium                  Benin                    Bolivia                 
##  [13] Bosnia and Herzegovina   Botswana                 Brazil                  
##  [16] Bulgaria                 Burkina Faso             Burundi                 
##  [19] Cambodia                 Cameroon                 Canada                  
##  [22] Central African Republic Chad                     Chile                   
##  [25] China                    Colombia                 Comoros                 
##  [28] Congo, Dem. Rep.         Congo, Rep.              Costa Rica              
##  [31] Cote d&#39;Ivoire            Croatia                  Cuba                    
##  [34] Czech Republic           Denmark                  Djibouti                
##  [37] Dominican Republic       Ecuador                  Egypt                   
##  [40] El Salvador              Equatorial Guinea        Eritrea                 
##  [43] Ethiopia                 Finland                  France                  
##  [46] Gabon                    Gambia                   Germany                 
##  [49] Ghana                    Greece                   Guatemala               
##  [52] Guinea                   Guinea-Bissau            Haiti                   
##  [55] Honduras                 Hong Kong, China         Hungary                 
##  [58] Iceland                  India                    Indonesia               
##  [61] Iran                     Iraq                     Ireland                 
##  [64] Israel                   Italy                    Jamaica                 
##  [67] Japan                    Jordan                   Kenya                   
##  [70] Korea, Dem. Rep.         Korea, Rep.              Kuwait                  
##  [73] Lebanon                  Lesotho                  Liberia                 
##  [76] Libya                    Madagascar               Malawi                  
##  [79] Malaysia                 Mali                     Mauritania              
##  [82] Mauritius                Mexico                   Mongolia                
##  [85] Montenegro               Morocco                  Mozambique              
##  [88] Myanmar                  Namibia                  Nepal                   
##  [91] Netherlands              New Zealand              Nicaragua               
##  [94] Niger                    Nigeria                  Norway                  
##  [97] Oman                     Pakistan                 Panama                  
## [100] Paraguay                 Peru                     Philippines             
## [103] Poland                   Portugal                 Puerto Rico             
## [106] Reunion                  Romania                  Rwanda                  
## [109] Sao Tome and Principe    Saudi Arabia             Senegal                 
## [112] Serbia                   Sierra Leone             Singapore               
## [115] Slovak Republic          Slovenia                 Somalia                 
## [118] South Africa             Spain                    Sri Lanka               
## [121] Sudan                    Swaziland                Sweden                  
## [124] Switzerland              Syria                    Taiwan                  
## [127] Tanzania                 Thailand                 Togo                    
## [130] Trinidad and Tobago      Tunisia                  Turkey                  
## [133] Uganda                   United Kingdom           United States           
## [136] Uruguay                  Venezuela                Vietnam                 
## [139] West Bank and Gaza       Yemen, Rep.              Zambia                  
## [142] Zimbabwe                
## 142 Levels: Afghanistan Albania Algeria Angola Argentina Australia ... Zimbabwe</code></pre>
<p>Fem el mateix per la variable Year.</p>
<pre class="r"><code>unique(gapminder$year) #### El número d&#39;anys que apareixen en aquesta base de dades</code></pre>
<pre><code>##  [1] 1952 1957 1962 1967 1972 1977 1982 1987 1992 1997 2002 2007</code></pre>
<p>Com comptem casos? Amb la funció lenght()</p>
<pre class="r"><code>length(gapminder$year) # Ens dona el número de casos de cada variable</code></pre>
<pre><code>## [1] 1704</code></pre>
<p>Si volem comptar el número d’etiquetes o valors fem el següent codi:</p>
<pre class="r"><code>length(unique(gapminder$year)) #Ens dona que només tenim 12 anys diferents (12 valors/categories)</code></pre>
<pre><code>## [1] 12</code></pre>
<p>Si volem en canvi, obtenir més informació de manera ràpida podem utilitzar el comandament summary():</p>
<pre class="r"><code>summary(gapminder$continent) ### Obtenim els casos per continent.</code></pre>
<pre><code>##   Africa Americas     Asia   Europe  Oceania 
##      624      300      396      360       24</code></pre>
<pre class="r"><code>summary(gapminder$country) ### Obtenim que son 12 casos per cada país. 12 observacions, 1 per any, de cada país.</code></pre>
<pre><code>##              Afghanistan                  Albania                  Algeria 
##                       12                       12                       12 
##                   Angola                Argentina                Australia 
##                       12                       12                       12 
##                  Austria                  Bahrain               Bangladesh 
##                       12                       12                       12 
##                  Belgium                    Benin                  Bolivia 
##                       12                       12                       12 
##   Bosnia and Herzegovina                 Botswana                   Brazil 
##                       12                       12                       12 
##                 Bulgaria             Burkina Faso                  Burundi 
##                       12                       12                       12 
##                 Cambodia                 Cameroon                   Canada 
##                       12                       12                       12 
## Central African Republic                     Chad                    Chile 
##                       12                       12                       12 
##                    China                 Colombia                  Comoros 
##                       12                       12                       12 
##         Congo, Dem. Rep.              Congo, Rep.               Costa Rica 
##                       12                       12                       12 
##            Cote d&#39;Ivoire                  Croatia                     Cuba 
##                       12                       12                       12 
##           Czech Republic                  Denmark                 Djibouti 
##                       12                       12                       12 
##       Dominican Republic                  Ecuador                    Egypt 
##                       12                       12                       12 
##              El Salvador        Equatorial Guinea                  Eritrea 
##                       12                       12                       12 
##                 Ethiopia                  Finland                   France 
##                       12                       12                       12 
##                    Gabon                   Gambia                  Germany 
##                       12                       12                       12 
##                    Ghana                   Greece                Guatemala 
##                       12                       12                       12 
##                   Guinea            Guinea-Bissau                    Haiti 
##                       12                       12                       12 
##                 Honduras         Hong Kong, China                  Hungary 
##                       12                       12                       12 
##                  Iceland                    India                Indonesia 
##                       12                       12                       12 
##                     Iran                     Iraq                  Ireland 
##                       12                       12                       12 
##                   Israel                    Italy                  Jamaica 
##                       12                       12                       12 
##                    Japan                   Jordan                    Kenya 
##                       12                       12                       12 
##         Korea, Dem. Rep.              Korea, Rep.                   Kuwait 
##                       12                       12                       12 
##                  Lebanon                  Lesotho                  Liberia 
##                       12                       12                       12 
##                    Libya               Madagascar                   Malawi 
##                       12                       12                       12 
##                 Malaysia                     Mali               Mauritania 
##                       12                       12                       12 
##                Mauritius                   Mexico                 Mongolia 
##                       12                       12                       12 
##               Montenegro                  Morocco               Mozambique 
##                       12                       12                       12 
##                  Myanmar                  Namibia                    Nepal 
##                       12                       12                       12 
##              Netherlands              New Zealand                Nicaragua 
##                       12                       12                       12 
##                    Niger                  Nigeria                   Norway 
##                       12                       12                       12 
##                     Oman                 Pakistan                   Panama 
##                       12                       12                       12 
##                  (Other) 
##                      516</code></pre>
<pre class="r"><code>summary(gapminder$lifeExp) </code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   23.60   48.20   60.71   59.47   70.85   82.60</code></pre>
<p>Ara, en canvi, al ser una variable numèrica continua ens dona els estadístics descriptius habituals (mitjana, mediana, min, màxim i quartils).</p>
<pre class="r"><code>summary(gapminder$gdpPercap) ### Ens torna a donar els mateixos estadístics però de la variable PIB per cápita.</code></pre>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
##    241.2   1202.1   3531.8   7215.3   9325.5 113523.1</code></pre>
<p>Tot això ens ha hagut de proporcionar una bona imatge mental de les dades que treballarem.</p>
<p>Contesteu les següents preguntes:</p>
<ol style="list-style-type: decimal">
<li>En quin continent tenim més casos registrats? En quin menys?</li>
<li>Quina és l’esperança màxima de vida registrada? Quina és la mitjana d’esperança de vida?</li>
<li>I quin és el PIB per cápida màxim? I el minim?</li>
</ol>
</div>
</div>
<div id="transformar-una-base-de-dades" class="section level3">
<h3>Transformar una base de dades</h3>
<p>En l’anterior apartat hem realitzat una observació o exploració general d’una base de dades i d’algunes variables. Tanmateix, si volem extreure totes les potencialitats possibles a les dades ens cal transformar-les. En base a aquesta transformació de les dades podrem fer-nos preguntes més concretes sobre les dades que tenim. L’exploració passarà a ser més minuciosa i detallada.</p>
<p>En aquest apartat aprendrem a utilitzar el paquet de transformació de dades dplyr que inclou 6 grans funcions: filtrar, ordenar, seleccionar, mutar, resumir i agrupar.</p>
<div id="taula-1.-sis-funcions-bàsiques-del-paquet-dplyr-mas-2020" class="section level4">
<h4>Taula 1. Sis funcions bàsiques del paquet dplyr (Mas, 2020)</h4>
<div class="figure">
<img src="images/taula_funcions_dplyr.png" alt="" />
<p class="caption">taula_dplyr</p>
</div>
<p>Per treballar amb aquestes funcions que assenyala la taula utiltizarem la funció pipe(%&gt;%) que ens permet encadenar funcions de manera simultanea sempre i quan tinguin el primer argument en comú. La taula 9 ens ho explica:</p>
</div>
<div id="taula-2.-resum-funció-pipe" class="section level4">
<h4>Taula 2. Resum funció pipe()</h4>
<div class="figure">
<img src="images/taula_pipe.png" alt="" />
<p class="caption">taula_dplyr</p>
</div>
<p>####TAULA FUNCIONS PIPE</p>
<p>Atenció: és important que cada cop que transformem la base de dades ho guardem en un altre objecte per no perdre la informació real de la base de dades.</p>
<p>Abans de començar a aplicar les funcions, carreguem les llibreries i una base de dades. En aquest cas l’històric de sondeigs de l’ICPS que hem treballat anteriorment.</p>
<pre class="r"><code>library(tidyverse)
library(dplyr)</code></pre>
<p>Carreguem de nou les dades anteriors sobre l’enquesta de l’ICPS per aplicar-hi totes les funcions. També les convertim en un data frame amb la funció as.data.frame i comprovem amb glimpse() i class() si s’ha convertit en un.</p>
<pre class="r"><code>ICPS &lt;- read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;)</code></pre>
<pre><code>## re-encoding from CP1252</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Duplicated levels in factor V371: Per mi és tan important la llibertat com la
## igualtat, però s</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 added in variable: V480</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 added in variable: V481</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 added in variable: V482</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
## 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
## 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
## 60, 61, 62, 63, 64 added in variable: V519</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
## 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
## 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
## 60, 61, 62, 67 added in variable: V520</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
## 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
## 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 60, 61, 62, 64
## added in variable: V521</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
## 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
## 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 58, 59, 62 added in
## variable: V522</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 6, 10, 11, 12, 14, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27,
## 28, 29, 31, 32, 34, 36, 37, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 50, 51, 52, 53,
## 54, 55, 57, 60 added in variable: V523</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 9, 12, 13, 17, 21, 22, 23, 25, 29, 30, 32, 37, 40, 41, 43, 45,
## 46, 49, 50, 52, 55, 56, 57, 62 added in variable: V524</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 25, 28, 31, 33, 42, 44, 45, 47, 49, 50, 59 added in variable:
## V525</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 30, 51, 55 added in variable: V526</code></pre>
<pre><code>## Warning in read.spss(&quot;./dades/Sondeig Opinio Catalunya base integrada_ICPS.sav&quot;):
## Undeclared level(s) 32 added in variable: V527</code></pre>
<pre class="r"><code>ICPS &lt;- as.data.frame(ICPS)
class(ICPS)</code></pre>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<pre class="r"><code>#names(ICPS)
#glimpse(ICPS)
as.tibble(ICPS)</code></pre>
<pre><code>## # A tibble: 37,972 x 573
##    NUMERO ANY    ID01  ID02  ID03  ID11  ID12  ID13  ID14  ID15  ID21 ID22H ID22D
##     &lt;dbl&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1      5 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  2     10 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  3     12 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  4     15 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  5     42 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  6    134 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  7    149 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  8    150 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
##  9    209 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
## 10    219 1991     NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
## # ... with 37,962 more rows, and 560 more variables: ID31 &lt;dbl&gt;, ID41 &lt;dbl&gt;,
## #   IDI &lt;fct&gt;, V001 &lt;fct&gt;, V002 &lt;fct&gt;, V003 &lt;fct&gt;, V004 &lt;fct&gt;, V005 &lt;fct&gt;,
## #   V006 &lt;fct&gt;, V007 &lt;fct&gt;, V008 &lt;fct&gt;, V009 &lt;fct&gt;, V010 &lt;fct&gt;, V011 &lt;fct&gt;,
## #   V012 &lt;fct&gt;, V013 &lt;fct&gt;, V014 &lt;fct&gt;, V015 &lt;fct&gt;, V016 &lt;fct&gt;, V017 &lt;fct&gt;,
## #   V018 &lt;fct&gt;, V019 &lt;fct&gt;, V020 &lt;fct&gt;, V021 &lt;fct&gt;, V022 &lt;fct&gt;, V023 &lt;fct&gt;,
## #   V024 &lt;fct&gt;, V025 &lt;fct&gt;, V026 &lt;fct&gt;, V027 &lt;fct&gt;, V028 &lt;fct&gt;, V029 &lt;fct&gt;,
## #   V030 &lt;fct&gt;, V031 &lt;fct&gt;, V032 &lt;fct&gt;, V033 &lt;fct&gt;, V034 &lt;fct&gt;, V035 &lt;fct&gt;,
## #   V036 &lt;fct&gt;, V037 &lt;fct&gt;, V038 &lt;fct&gt;, V039 &lt;fct&gt;, V040 &lt;fct&gt;, V041 &lt;fct&gt;,
## #   V042 &lt;fct&gt;, V043 &lt;fct&gt;, V044 &lt;fct&gt;, V045 &lt;fct&gt;, V046 &lt;fct&gt;, V047 &lt;fct&gt;,
## #   V048 &lt;fct&gt;, V049 &lt;fct&gt;, V050 &lt;fct&gt;, V051 &lt;fct&gt;, V052 &lt;fct&gt;, V053 &lt;fct&gt;,
## #   V054 &lt;fct&gt;, V055 &lt;fct&gt;, V056 &lt;fct&gt;, V057 &lt;fct&gt;, V058 &lt;fct&gt;, V059 &lt;fct&gt;,
## #   V060 &lt;fct&gt;, V061 &lt;fct&gt;, V062 &lt;fct&gt;, V063 &lt;fct&gt;, V064 &lt;fct&gt;, V065 &lt;fct&gt;,
## #   V066 &lt;fct&gt;, V067 &lt;fct&gt;, V068 &lt;fct&gt;, V069 &lt;fct&gt;, V070 &lt;fct&gt;, V071 &lt;fct&gt;,
## #   V072 &lt;fct&gt;, V073 &lt;fct&gt;, V074 &lt;fct&gt;, V075 &lt;fct&gt;, V076 &lt;fct&gt;, V077 &lt;fct&gt;,
## #   V078 &lt;fct&gt;, V079 &lt;fct&gt;, V080 &lt;fct&gt;, V081 &lt;fct&gt;, V082 &lt;fct&gt;, V083 &lt;fct&gt;,
## #   V084 &lt;fct&gt;, V085 &lt;fct&gt;, V086 &lt;fct&gt;, V087 &lt;fct&gt;, V088 &lt;fct&gt;, V089 &lt;fct&gt;,
## #   V090 &lt;fct&gt;, V091 &lt;fct&gt;, V092 &lt;fct&gt;, V093 &lt;fct&gt;, V094 &lt;fct&gt;, V095 &lt;fct&gt;,
## #   V096 &lt;fct&gt;, V097 &lt;fct&gt;, ...</code></pre>
</div>
<div id="filtrar-filter" class="section level4">
<h4>1. Filtrar (filter)</h4>
<p>La funció filtrar ens permet crear un subconjunt de files d’un marc de dades determinat sobre la base d’una o més condcions lògiques.</p>
<p>Suposem que volem veure només les observacions d’una sola provincia: en aquest cas la de Girona. Com veiem hi ha una variable que es diu “PROVINCIA”. Apliquem la funció filter() amb la funció pipe().</p>
<pre class="r"><code>table(ICPS$PROVINCIA) ### Observem quans casos hi ha a Girona i quina és l&#39;etiqueta exacte.</code></pre>
<pre><code>## 
## Barcelona    Girona    Lleida Tarragona 
##     21365      5739      5123      5745</code></pre>
<pre class="r"><code>ICPS_Girona &lt;- ICPS %&gt;% filter(PROVINCIA == &quot;Girona&quot;) ### Filtrem usant pipe() i filter()
#glimpse(ICPS_Girona) ### Analtizem la nova base de dades
table(ICPS_Girona$PROVINCIA) ### Comprovem el nombre de casos.</code></pre>
<pre><code>## 
## Barcelona    Girona    Lleida Tarragona 
##         0      5739         0         0</code></pre>
<p>Hem aconseguit filtrar la base de dades de l’enquesta del CEO per els casos de la provincia de Girona.</p>
<p>Provem ara a realitzar dos filtratges a la vegada.</p>
<pre class="r"><code>ICPS_Tarragona_2010 &lt;- ICPS %&gt;% filter(PROVINCIA == &quot;Tarragona&quot;) %&gt;% filter(ANY == &quot;2010&quot;)
#glimpse(ICPS_Tarragona_2010)
table(ICPS_Tarragona_2010$PROVINCIA)</code></pre>
<pre><code>## 
## Barcelona    Girona    Lleida Tarragona 
##         0         0         0       400</code></pre>
<pre class="r"><code>table(ICPS_Tarragona_2010$ANY)</code></pre>
<pre><code>## 
## 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005 2006 
##    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0 
## 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 
##    0    0    0  400    0    0    0    0    0    0</code></pre>
<p>Aquí tenim un doble filtratge: per una banda els casos de la provincia de Tarragona i per l’altre els casos que tenen 24 anys o meys. Això ens diu que a només hi ha 9 casos que compleixin aquests requisits.</p>
<p>Realitzem un nou filtratge. En aquest cas tenint en compte les preferències en les relacions CAT-ESP.</p>
<pre class="r"><code>table(ICPS$V182)</code></pre>
<pre><code>## 
##              Una regió d&#39;Espanya Una Comunitat Autònoma d&#39;Espanya 
##                             3487                            17499 
##   Un Estat d&#39;una Espanya Federal             Un Estat independent 
##                             6330                             8579 
##                           Altres                           No sap 
##                              243                             1672 
##                      No contesta 
##                              162</code></pre>
<pre class="r"><code>ICPS_indy &lt;- ICPS %&gt;% filter(V182 == &quot;Un Estat independent&quot;)
#glimpse(ICPS_indy)</code></pre>
<p>Per acabar fem un doble filtratge més: Estat independent i sexe dona.</p>
<pre class="r"><code>table(ICPS$SEXE)</code></pre>
<pre><code>## 
##  Home  Dona 
## 18563 19409</code></pre>
<pre class="r"><code>ICPS_indy_dona &lt;- ICPS %&gt;% filter(V182 == &quot;Un Estat independent&quot;) %&gt;% filter(SEXE == &quot;Dona&quot;) %&gt;% droplevels() 
#glimpse(ICPS_indy_dona)
table(ICPS_indy_dona$SEXE)</code></pre>
<pre><code>## 
## Dona 
## 4229</code></pre>
<p>A través d’aquests filtratges podem estudiar les variables segmentades pels casos que ens interessen.</p>
<pre class="r"><code>table(ICPS$V182, ICPS$SEXE) ###Comprovació amb les variables originals</code></pre>
<pre><code>##                                   
##                                    Home Dona
##   Una regió d&#39;Espanya              1601 1886
##   Una Comunitat Autònoma d&#39;Espanya 7795 9704
##   Un Estat d&#39;una Espanya Federal   3952 2378
##   Un Estat independent             4350 4229
##   Altres                            144   99
##   No sap                            650 1022
##   No contesta                        71   91</code></pre>
</div>
<div id="ordenar" class="section level4">
<h4>2. Ordenar</h4>
<p>La función arrange() simplement ordena les files de manera ascendent o descendent a partir dels valors d’una determinada variable o columna. És una funció útil per a ordenar casos a partir d’una variable numèrica continua o discreta. Provem amb les dades de gapminder.</p>
<pre class="r"><code>a &lt;- gapminder %&gt;% arrange(lifeExp)
#glimpse(a)</code></pre>
<p>Ens dona tota la base de dades de gapminder ordenada de menor a major esperança de vida. Si volem fer-ho al revés.</p>
<pre class="r"><code>b &lt;- gapminder %&gt;% arrange(desc(lifeExp))
#glimpse(b)</code></pre>
<p>Ara ens ho ordena de més esperança de vida a menys.</p>
<pre class="r"><code>c &lt;- gapminder %&gt;% arrange(gdpPercap)
#glimpse(c)</code></pre>
<p>Ordenada per menys a més PIB per cápita.</p>
</div>
<div id="seleccionar" class="section level4">
<h4>3. Seleccionar</h4>
<p>La funció select() ens permet seleccionar el número de columnes, és a dir, variables amb les que volguem operar. Aquesta funció ens permet crear bases de dades més manegables i orientades a les variables que volem analitzar.</p>
<p>Provem com funciona. Seleccionem variables relacionades amb les Relacions CAT-ESP de l’ICPS.</p>
<pre class="r"><code>#V182 #### Model territorial
#V187 #### Proximitat a ESP
#V188 #### Proximitat a CAT

names(ICPS)</code></pre>
<pre><code>##   [1] &quot;NUMERO&quot;    &quot;ANY&quot;       &quot;ID01&quot;      &quot;ID02&quot;      &quot;ID03&quot;      &quot;ID11&quot;     
##   [7] &quot;ID12&quot;      &quot;ID13&quot;      &quot;ID14&quot;      &quot;ID15&quot;      &quot;ID21&quot;      &quot;ID22H&quot;    
##  [13] &quot;ID22D&quot;     &quot;ID31&quot;      &quot;ID41&quot;      &quot;IDI&quot;       &quot;V001&quot;      &quot;V002&quot;     
##  [19] &quot;V003&quot;      &quot;V004&quot;      &quot;V005&quot;      &quot;V006&quot;      &quot;V007&quot;      &quot;V008&quot;     
##  [25] &quot;V009&quot;      &quot;V010&quot;      &quot;V011&quot;      &quot;V012&quot;      &quot;V013&quot;      &quot;V014&quot;     
##  [31] &quot;V015&quot;      &quot;V016&quot;      &quot;V017&quot;      &quot;V018&quot;      &quot;V019&quot;      &quot;V020&quot;     
##  [37] &quot;V021&quot;      &quot;V022&quot;      &quot;V023&quot;      &quot;V024&quot;      &quot;V025&quot;      &quot;V026&quot;     
##  [43] &quot;V027&quot;      &quot;V028&quot;      &quot;V029&quot;      &quot;V030&quot;      &quot;V031&quot;      &quot;V032&quot;     
##  [49] &quot;V033&quot;      &quot;V034&quot;      &quot;V035&quot;      &quot;V036&quot;      &quot;V037&quot;      &quot;V038&quot;     
##  [55] &quot;V039&quot;      &quot;V040&quot;      &quot;V041&quot;      &quot;V042&quot;      &quot;V043&quot;      &quot;V044&quot;     
##  [61] &quot;V045&quot;      &quot;V046&quot;      &quot;V047&quot;      &quot;V048&quot;      &quot;V049&quot;      &quot;V050&quot;     
##  [67] &quot;V051&quot;      &quot;V052&quot;      &quot;V053&quot;      &quot;V054&quot;      &quot;V055&quot;      &quot;V056&quot;     
##  [73] &quot;V057&quot;      &quot;V058&quot;      &quot;V059&quot;      &quot;V060&quot;      &quot;V061&quot;      &quot;V062&quot;     
##  [79] &quot;V063&quot;      &quot;V064&quot;      &quot;V065&quot;      &quot;V066&quot;      &quot;V067&quot;      &quot;V068&quot;     
##  [85] &quot;V069&quot;      &quot;V070&quot;      &quot;V071&quot;      &quot;V072&quot;      &quot;V073&quot;      &quot;V074&quot;     
##  [91] &quot;V075&quot;      &quot;V076&quot;      &quot;V077&quot;      &quot;V078&quot;      &quot;V079&quot;      &quot;V080&quot;     
##  [97] &quot;V081&quot;      &quot;V082&quot;      &quot;V083&quot;      &quot;V084&quot;      &quot;V085&quot;      &quot;V086&quot;     
## [103] &quot;V087&quot;      &quot;V088&quot;      &quot;V089&quot;      &quot;V090&quot;      &quot;V091&quot;      &quot;V092&quot;     
## [109] &quot;V093&quot;      &quot;V094&quot;      &quot;V095&quot;      &quot;V096&quot;      &quot;V097&quot;      &quot;V098&quot;     
## [115] &quot;V099&quot;      &quot;V100&quot;      &quot;V101&quot;      &quot;V102&quot;      &quot;V103&quot;      &quot;V104&quot;     
## [121] &quot;V105&quot;      &quot;V106&quot;      &quot;V107&quot;      &quot;V108&quot;      &quot;V109&quot;      &quot;V110&quot;     
## [127] &quot;V111&quot;      &quot;V112&quot;      &quot;V113&quot;      &quot;V114&quot;      &quot;V115&quot;      &quot;V116&quot;     
## [133] &quot;V117&quot;      &quot;V118&quot;      &quot;V119&quot;      &quot;V120&quot;      &quot;V121&quot;      &quot;V122&quot;     
## [139] &quot;V123&quot;      &quot;V124&quot;      &quot;V125&quot;      &quot;V126&quot;      &quot;V127&quot;      &quot;V128&quot;     
## [145] &quot;V129&quot;      &quot;V130&quot;      &quot;V131&quot;      &quot;V132&quot;      &quot;V133&quot;      &quot;V134&quot;     
## [151] &quot;V135&quot;      &quot;V136&quot;      &quot;V137&quot;      &quot;V138&quot;      &quot;V139&quot;      &quot;V140&quot;     
## [157] &quot;V141&quot;      &quot;V142&quot;      &quot;V143&quot;      &quot;V144&quot;      &quot;V145&quot;      &quot;V146&quot;     
## [163] &quot;V147&quot;      &quot;V148&quot;      &quot;V149&quot;      &quot;V150&quot;      &quot;V151&quot;      &quot;V152&quot;     
## [169] &quot;V153&quot;      &quot;V154&quot;      &quot;V155&quot;      &quot;V156&quot;      &quot;V157&quot;      &quot;V158&quot;     
## [175] &quot;V159&quot;      &quot;V160&quot;      &quot;V161&quot;      &quot;V162&quot;      &quot;V163&quot;      &quot;V164&quot;     
## [181] &quot;V165&quot;      &quot;V166&quot;      &quot;V167&quot;      &quot;V168&quot;      &quot;V169&quot;      &quot;V170&quot;     
## [187] &quot;V171&quot;      &quot;V172&quot;      &quot;V173&quot;      &quot;V174&quot;      &quot;V175&quot;      &quot;V176&quot;     
## [193] &quot;V177&quot;      &quot;V178&quot;      &quot;V179&quot;      &quot;V180&quot;      &quot;V181&quot;      &quot;V182&quot;     
## [199] &quot;V183&quot;      &quot;V184&quot;      &quot;V185&quot;      &quot;V186&quot;      &quot;V187&quot;      &quot;V188&quot;     
## [205] &quot;V189&quot;      &quot;V190&quot;      &quot;V191&quot;      &quot;V192&quot;      &quot;V193&quot;      &quot;V194&quot;     
## [211] &quot;V195&quot;      &quot;V196&quot;      &quot;V197&quot;      &quot;V198&quot;      &quot;V199&quot;      &quot;V200&quot;     
## [217] &quot;V201&quot;      &quot;V202&quot;      &quot;V203&quot;      &quot;V204&quot;      &quot;V205&quot;      &quot;V206&quot;     
## [223] &quot;V207&quot;      &quot;V208&quot;      &quot;V209&quot;      &quot;V210&quot;      &quot;V211&quot;      &quot;V212&quot;     
## [229] &quot;V213&quot;      &quot;V214&quot;      &quot;V215&quot;      &quot;V216&quot;      &quot;V217&quot;      &quot;V218&quot;     
## [235] &quot;V219&quot;      &quot;V220&quot;      &quot;V221&quot;      &quot;V222&quot;      &quot;V223&quot;      &quot;V224&quot;     
## [241] &quot;V225&quot;      &quot;V226&quot;      &quot;V227&quot;      &quot;V228&quot;      &quot;V229&quot;      &quot;V230&quot;     
## [247] &quot;V231&quot;      &quot;V232&quot;      &quot;V233&quot;      &quot;V234&quot;      &quot;V235&quot;      &quot;V236&quot;     
## [253] &quot;V237&quot;      &quot;V238&quot;      &quot;V239&quot;      &quot;V240&quot;      &quot;V241&quot;      &quot;V242&quot;     
## [259] &quot;V243&quot;      &quot;V244&quot;      &quot;V245&quot;      &quot;V246&quot;      &quot;V247&quot;      &quot;V248&quot;     
## [265] &quot;V249&quot;      &quot;V250&quot;      &quot;V251&quot;      &quot;V252&quot;      &quot;V253&quot;      &quot;V254&quot;     
## [271] &quot;V255&quot;      &quot;V256&quot;      &quot;V257&quot;      &quot;V258&quot;      &quot;V259&quot;      &quot;V260&quot;     
## [277] &quot;V261&quot;      &quot;V262&quot;      &quot;V263&quot;      &quot;V264&quot;      &quot;V265&quot;      &quot;V266&quot;     
## [283] &quot;V267&quot;      &quot;V268&quot;      &quot;V269&quot;      &quot;V270&quot;      &quot;V271&quot;      &quot;V272&quot;     
## [289] &quot;V273&quot;      &quot;V274&quot;      &quot;V275&quot;      &quot;V276&quot;      &quot;V277&quot;      &quot;V278&quot;     
## [295] &quot;V279&quot;      &quot;V280&quot;      &quot;V281&quot;      &quot;V282&quot;      &quot;V283&quot;      &quot;V284&quot;     
## [301] &quot;V285&quot;      &quot;V286&quot;      &quot;V287&quot;      &quot;V288&quot;      &quot;V289&quot;      &quot;V290&quot;     
## [307] &quot;V291&quot;      &quot;V292&quot;      &quot;V293&quot;      &quot;V294&quot;      &quot;V295&quot;      &quot;V296&quot;     
## [313] &quot;V297&quot;      &quot;V298&quot;      &quot;V299&quot;      &quot;V300&quot;      &quot;V301&quot;      &quot;V302&quot;     
## [319] &quot;V303&quot;      &quot;V304&quot;      &quot;V305&quot;      &quot;V306&quot;      &quot;V307&quot;      &quot;V308&quot;     
## [325] &quot;V309&quot;      &quot;V310&quot;      &quot;V311&quot;      &quot;V312&quot;      &quot;V313&quot;      &quot;V314&quot;     
## [331] &quot;V315&quot;      &quot;V316&quot;      &quot;V317&quot;      &quot;V318&quot;      &quot;V319&quot;      &quot;V320&quot;     
## [337] &quot;V321&quot;      &quot;V322&quot;      &quot;V323&quot;      &quot;V324&quot;      &quot;V325&quot;      &quot;V326&quot;     
## [343] &quot;V327&quot;      &quot;V328&quot;      &quot;V329&quot;      &quot;V330&quot;      &quot;V331&quot;      &quot;V332&quot;     
## [349] &quot;V333&quot;      &quot;V334&quot;      &quot;V335&quot;      &quot;V336&quot;      &quot;V337&quot;      &quot;V338&quot;     
## [355] &quot;V339&quot;      &quot;V340&quot;      &quot;V341&quot;      &quot;V342&quot;      &quot;V343&quot;      &quot;V344&quot;     
## [361] &quot;V345&quot;      &quot;V346&quot;      &quot;V347&quot;      &quot;V348&quot;      &quot;V349&quot;      &quot;V350&quot;     
## [367] &quot;V351&quot;      &quot;V352&quot;      &quot;v352_2&quot;    &quot;V353&quot;      &quot;v353_2&quot;    &quot;V354&quot;     
## [373] &quot;v354_2&quot;    &quot;V355&quot;      &quot;V356&quot;      &quot;V357&quot;      &quot;V358&quot;      &quot;V359&quot;     
## [379] &quot;V360&quot;      &quot;V361&quot;      &quot;V362&quot;      &quot;V363&quot;      &quot;V364&quot;      &quot;V365&quot;     
## [385] &quot;V366&quot;      &quot;V367&quot;      &quot;V368&quot;      &quot;V369&quot;      &quot;V370&quot;      &quot;V371&quot;     
## [391] &quot;V372&quot;      &quot;V373&quot;      &quot;V374&quot;      &quot;V375&quot;      &quot;V376&quot;      &quot;V377&quot;     
## [397] &quot;V378&quot;      &quot;V379&quot;      &quot;V380&quot;      &quot;V381&quot;      &quot;V382&quot;      &quot;V383&quot;     
## [403] &quot;V384&quot;      &quot;V385&quot;      &quot;V386&quot;      &quot;V387&quot;      &quot;V388&quot;      &quot;V389&quot;     
## [409] &quot;V390&quot;      &quot;V391&quot;      &quot;V392&quot;      &quot;V393&quot;      &quot;V394&quot;      &quot;V395&quot;     
## [415] &quot;V396&quot;      &quot;V397&quot;      &quot;V398&quot;      &quot;V399&quot;      &quot;V400&quot;      &quot;V401&quot;     
## [421] &quot;V402&quot;      &quot;V403&quot;      &quot;V404&quot;      &quot;V405&quot;      &quot;V406&quot;      &quot;V407&quot;     
## [427] &quot;V408&quot;      &quot;V409&quot;      &quot;V410&quot;      &quot;V411&quot;      &quot;V412&quot;      &quot;V413&quot;     
## [433] &quot;V414&quot;      &quot;V415&quot;      &quot;V416&quot;      &quot;V417&quot;      &quot;V418&quot;      &quot;V419&quot;     
## [439] &quot;V420&quot;      &quot;V421&quot;      &quot;V422&quot;      &quot;V423&quot;      &quot;V424&quot;      &quot;V425&quot;     
## [445] &quot;V426&quot;      &quot;V427&quot;      &quot;V428&quot;      &quot;V429&quot;      &quot;V430&quot;      &quot;V431&quot;     
## [451] &quot;V432&quot;      &quot;V433&quot;      &quot;V434&quot;      &quot;V435&quot;      &quot;V436&quot;      &quot;V437&quot;     
## [457] &quot;V438&quot;      &quot;V439&quot;      &quot;V440&quot;      &quot;V441&quot;      &quot;V442&quot;      &quot;V443&quot;     
## [463] &quot;V444&quot;      &quot;V445&quot;      &quot;V446&quot;      &quot;V447&quot;      &quot;V448&quot;      &quot;V449&quot;     
## [469] &quot;V450&quot;      &quot;V451&quot;      &quot;V452&quot;      &quot;V453&quot;      &quot;V454&quot;      &quot;V455&quot;     
## [475] &quot;V456&quot;      &quot;V457&quot;      &quot;V458&quot;      &quot;V459&quot;      &quot;V460&quot;      &quot;V461&quot;     
## [481] &quot;V462&quot;      &quot;V463&quot;      &quot;V464&quot;      &quot;V465&quot;      &quot;V466&quot;      &quot;V467&quot;     
## [487] &quot;V468&quot;      &quot;V469&quot;      &quot;V470&quot;      &quot;V471&quot;      &quot;V472&quot;      &quot;V473&quot;     
## [493] &quot;V474&quot;      &quot;V475&quot;      &quot;V476&quot;      &quot;V477&quot;      &quot;V478&quot;      &quot;V479&quot;     
## [499] &quot;V480&quot;      &quot;V481&quot;      &quot;V482&quot;      &quot;V483&quot;      &quot;V484&quot;      &quot;V485&quot;     
## [505] &quot;V486&quot;      &quot;V487&quot;      &quot;V488&quot;      &quot;V489&quot;      &quot;V490&quot;      &quot;V491&quot;     
## [511] &quot;V492&quot;      &quot;V493&quot;      &quot;V494&quot;      &quot;V495&quot;      &quot;V496&quot;      &quot;V497&quot;     
## [517] &quot;V498&quot;      &quot;V499&quot;      &quot;V500&quot;      &quot;V501&quot;      &quot;V502&quot;      &quot;V503&quot;     
## [523] &quot;SEXE&quot;      &quot;EDAT&quot;      &quot;V504&quot;      &quot;V505&quot;      &quot;V506&quot;      &quot;V507&quot;     
## [529] &quot;V508&quot;      &quot;V509&quot;      &quot;V510&quot;      &quot;V511&quot;      &quot;V512&quot;      &quot;V513&quot;     
## [535] &quot;V514&quot;      &quot;V515&quot;      &quot;V516&quot;      &quot;V517&quot;      &quot;V518&quot;      &quot;V519&quot;     
## [541] &quot;V520&quot;      &quot;V521&quot;      &quot;V522&quot;      &quot;V523&quot;      &quot;V524&quot;      &quot;V525&quot;     
## [547] &quot;V526&quot;      &quot;V527&quot;      &quot;V528&quot;      &quot;V529&quot;      &quot;V530&quot;      &quot;V531&quot;     
## [553] &quot;V532&quot;      &quot;V533&quot;      &quot;V534&quot;      &quot;V535&quot;      &quot;V536&quot;      &quot;V537&quot;     
## [559] &quot;V538&quot;      &quot;V539&quot;      &quot;V540&quot;      &quot;V541&quot;      &quot;V542&quot;      &quot;V543&quot;     
## [565] &quot;V544&quot;      &quot;V545&quot;      &quot;V546&quot;      &quot;V547&quot;      &quot;V548&quot;      &quot;PROVINCIA&quot;
## [571] &quot;DIMENSIO&quot;  &quot;DISTRICTE&quot; &quot;PES&quot;</code></pre>
<pre class="r"><code>ICPS_nacional &lt;- ICPS %&gt;% select(V182,V187,V188)
#glimpse(ICPS_nacional)</code></pre>
<p>Hem creat una base de dades amb tots els casos i només 3 variables vinculades al tema nacional.</p>
</div>
<div id="mutar" class="section level4">
<h4>4. Mutar</h4>
<p>La funció de mutate() ens permet transformar els valors d’una determinada variable o crear una de nova a partir de les dades ja existents. Si el primer que especifiquem dins de la funció mutate es el nom de la columna que volem transformar, R ens sobreescriurà els valors en aquesta mateixa columna. Si el que fem és indicar el nom de la columna nova que no existeix dins d’aquest marc de dades, R ens mantindrà l’origianl i crearà una de nova.</p>
<p>Primer cas:</p>
<pre class="r"><code>gapminder</code></pre>
<pre><code>## # A tibble: 1,704 x 6
##    country     continent  year lifeExp      pop gdpPercap
##    &lt;fct&gt;       &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;
##  1 Afghanistan Asia       1952    28.8  8425333      779.
##  2 Afghanistan Asia       1957    30.3  9240934      821.
##  3 Afghanistan Asia       1962    32.0 10267083      853.
##  4 Afghanistan Asia       1967    34.0 11537966      836.
##  5 Afghanistan Asia       1972    36.1 13079460      740.
##  6 Afghanistan Asia       1977    38.4 14880372      786.
##  7 Afghanistan Asia       1982    39.9 12881816      978.
##  8 Afghanistan Asia       1987    40.8 13867957      852.
##  9 Afghanistan Asia       1992    41.7 16317921      649.
## 10 Afghanistan Asia       1997    41.8 22227415      635.
## # ... with 1,694 more rows</code></pre>
<pre class="r"><code>gapminder %&gt;% mutate(pop = pop/1000000) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 6
##   country     continent  year lifeExp   pop gdpPercap
##   &lt;fct&gt;       &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
## 1 Afghanistan Asia       1952    28.8  8.43      779.
## 2 Afghanistan Asia       1957    30.3  9.24      821.
## 3 Afghanistan Asia       1962    32.0 10.3       853.
## 4 Afghanistan Asia       1967    34.0 11.5       836.
## 5 Afghanistan Asia       1972    36.1 13.1       740.
## 6 Afghanistan Asia       1977    38.4 14.9       786.</code></pre>
<p>La columna pop ha canviat de l’original a l’actual amb l’operació realitzada.</p>
<p>Segon cas:</p>
<pre class="r"><code>gapminder %&gt;% mutate(gdp = gdpPercap*pop) %&gt;% head()</code></pre>
<pre><code>## # A tibble: 6 x 7
##   country     continent  year lifeExp      pop gdpPercap          gdp
##   &lt;fct&gt;       &lt;fct&gt;     &lt;int&gt;   &lt;dbl&gt;    &lt;int&gt;     &lt;dbl&gt;        &lt;dbl&gt;
## 1 Afghanistan Asia       1952    28.8  8425333      779.  6567086330.
## 2 Afghanistan Asia       1957    30.3  9240934      821.  7585448670.
## 3 Afghanistan Asia       1962    32.0 10267083      853.  8758855797.
## 4 Afghanistan Asia       1967    34.0 11537966      836.  9648014150.
## 5 Afghanistan Asia       1972    36.1 13079460      740.  9678553274.
## 6 Afghanistan Asia       1977    38.4 14880372      786. 11697659231.</code></pre>
<p>Afegeix la columna gdp que hem creat nova fruit de multiplicar PIB per cápita i població total. Això ens dona el PIB del país.</p>
</div>
<div id="resumir" class="section level4">
<h4>5. Resumir</h4>
<p>La funció summarize() ens resumeix en un únic valor les dades d’una columna a partir d’una determinada operació matemàtica. Veiem com funciona:</p>
<p>Provem. Seleccionem només països d’Àfrica a l’any 1962 amb filter().</p>
<pre class="r"><code>table(gapminder$year)</code></pre>
<pre><code>## 
## 1952 1957 1962 1967 1972 1977 1982 1987 1992 1997 2002 2007 
##  142  142  142  142  142  142  142  142  142  142  142  142</code></pre>
<pre class="r"><code>gap_africa_1962&lt;- gapminder %&gt;% filter(continent == &quot;Africa&quot;) %&gt;% 
  filter(year == &quot;1962&quot;)

#glimpse(gap_africa_1962)

gap_africa_1962 %&gt;% summarize(tpop = sum(pop), 
                              mean_gdpcap = mean(gdpPercap, na.rm = TRUE),
                              prop = mean(gdpPercap &gt; mean_gdpcap),
                              esp = sum(lifeExp &gt; 60), count = n())</code></pre>
<pre><code>## # A tibble: 1 x 5
##        tpop mean_gdpcap  prop   esp count
##       &lt;int&gt;       &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt;
## 1 296516865       1598. 0.327     1    52</code></pre>
<p>Què ens dona aquesta gran funció? Una taula on apareix la següent informació:</p>
<ol style="list-style-type: decimal">
<li>Selecciona tots els casos d’Àfrica a l’any 1962.</li>
<li>La nova variable tpop ens suma la població de tots els països africans filtrats en el continent.</li>
<li>La variable mean_gdpcap ens calcula la mitjana del producte interior brut.</li>
<li>esp ens dona el número de països amb una esperança de vida superior de 60 anys.</li>
<li>count() ens recompta les observacions filtrades.</li>
</ol>
</div>
<div id="agrupar" class="section level4">
<h4>6. Agrupar</h4>
<p>La funció group_by() s’ha d’aplicar en combinació amb altres variables. Aquesta opció ens permet agrupar algunes funcions seguint per les categories d’altres variables. Normalment hem de combinar aquesta funció amb summarize().</p>
<pre class="r"><code>gapminder %&gt;% filter(year == 1952) %&gt;% group_by(continent) %&gt;% 
  summarize(tpop = sum(pop), 
                        mean_gdpcap = mean(gdpPercap, na.rm = TRUE),
                        prop = mean(gdpPercap &gt; mean_gdpcap),
                        esp = sum(lifeExp &gt; 60), count = n())</code></pre>
<pre><code>## # A tibble: 5 x 6
##   continent       tpop mean_gdpcap   prop   esp count
## * &lt;fct&gt;          &lt;int&gt;       &lt;dbl&gt;  &lt;dbl&gt; &lt;int&gt; &lt;int&gt;
## 1 Africa     237640501       1253. 0.327      0    52
## 2 Americas   345152446       4079. 0.24       6    25
## 3 Asia      1395357351       5195. 0.0909     4    33
## 4 Europe     418120846       5661. 0.433     23    30
## 5 Oceania     10686006      10298. 0.5        2     2</code></pre>
<p>Aquest codi ens permet agrupar per ciutat i ens resumeix la variable amount amb la mitjana.</p>
<p><strong>Conclusió final</strong>: un codi amb més operacions no és necessariament un codi millor. Un bon codi és aquell que ens ajuda a transformar les dades de manera que ens permeti respondre les preguntes que ens fem (Mas, 2020)</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
